In [27]:
import pandas as pd
import numpy as np

## Series

In [3]:
age = pd.Series([1,2,3,4,5,6])
print(age)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [4]:
name = pd.Series(["abc", "xyz", "pqr", "sdf"])
name

0    abc
1    xyz
2    pqr
3    sdf
dtype: str

## Dataframe

In [5]:
d = {"name": ["abc", "xyz", "pqr", None], "age": [10, 40, None, 30]}

df = pd.DataFrame(d)
df

  name   age
0  abc  10.0
1  xyz  40.0
2  pqr   NaN
3  NaN  30.0

In [24]:
d2 = {
    "name" : name,
    "age" : age
}

df2 = pd.DataFrame(d2, index=[6,5,4,3,2,1])
df2

  name  age
6  NaN  NaN
5  NaN  6.0
4  NaN  5.0
3  sdf  4.0
2  pqr  3.0
1  xyz  2.0

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      float64
dtypes: float64(1), str(1)
memory usage: 196.0 bytes

In [32]:
n_df = df2.set_index(np.array([6,5,4,3,2,1]))
n_df

  name  age
6  NaN  NaN
5  NaN  6.0
4  NaN  5.0
3  sdf  4.0
2  pqr  3.0
1  xyz  2.0

In [8]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     6 non-null      int64
dtypes: int64(1), str(1)
memory usage: 228.0 bytes

In [9]:
df2.columns

Index(['name', 'age'], dtype='str')

In [10]:
age = df2["age"]
age

0    1
1    2
2    3
3    4
4    5
5    6
Name: age, dtype: int64

In [11]:
type(age), type(df2)

(pandas.Series, pandas.DataFrame)

In [12]:
fil = df2[(df2["age"] % 2 == 0)]
fil

  name  age
1  xyz    2
3  sdf    4
5  NaN    6

In [13]:
fil = df2[df2.isna().any(axis=1)]
fil

  name  age
4  NaN    5
5  NaN    6

In [14]:
fil = df2[df2["name"].isna()]
fil

  name  age
4  NaN    5
5  NaN    6

In [16]:
fil = df2[df2["name"].isna()].reset_index()
fil

   index name  age
0      4  NaN    5
1      5  NaN    6

In [17]:
fil = df2[df2["name"].isna()].reset_index(drop=True)
fil

  name  age
0  NaN    5
1  NaN    6