##### Dataset Practice

In [115]:
# import pandas as pd
# import numpy as np

# np.random.seed(42)

# n = 1000

# data = {
#     "id": range(1, n + 1),
#     "age": np.random.randint(18, 70, n),
#     "salary": np.random.randint(20000, 150000, n),
#     "experience_years": np.random.randint(0, 40, n),
#     "department": np.random.choice(["IT", "HR", "Sales", "Finance", "Marketing"], n),
#     "city": np.random.choice(["Ahmedabad", "Mumbai", "Delhi", "Bangalore", "Pune"], n),
#     "performance_score": np.round(np.random.uniform(1, 5, n), 2),
#     "bonus": np.random.randint(0, 50000, n),
#     "working_hours": np.random.randint(30, 60, n),
#     "satisfaction_level": np.round(np.random.uniform(0, 1, n), 2),
# }

# df = pd.DataFrame(data)

# # Add missing values randomly

# for col in ["age", "salary", "experience_years", "bonus", "performance_score"]:
#     df.loc[df.sample(frac=0.1).index, col] = np.nan

# df.to_csv("employee_dataset.csv", index=False)

# print("Dataset saved as employee_dataset.csv")

In [116]:
import pandas as pd

In [117]:
df = pd.read_csv("./dataset/employee_dataset.csv")
df

,id,age,salary,experience_years,department,city,performance_score,bonus,working_hours,satisfaction_level
0,1,56.0,125186.0,2.0,Finance,Bangalore,2.69,18771.0,56,0.69
1,2,69.0,54674.0,39.0,HR,Delhi,1.34,NaN,51,0.28
2,3,46.0,55854.0,33.0,Sales,Pune,3.43,42330.0,45,0.69
3,4,32.0,66271.0,39.0,HR,Mumbai,4.52,29320.0,30,0.31
4,5,60.0,93688.0,26.0,Marketing,Delhi,4.53,4340.0,41,0.76
...,...,...,...,...,...,...,...,...,...,...
995,996,60.0,145991.0,5.0,Finance,Delhi,1.84,29412.0,52,0.19
996,997,NaN,29516.0,18.0,Finance,Bangalore,3.97,21341.0,58,0.89
997,998,62.0,132863.0,36.0,IT,Delhi,1.10,32018.0,34,0.43
998,999,35.0,135005.0,3.0,Finance,Bangalore,2.42,9145.0,39,0.20
999,1000,55.0,22396.0,3.0,HR,Pune,4.12,42262.0,36,0.44

In [118]:
df.shape

(1000, 10)

In [119]:
df.columns, len(df.columns)

(Index(['id', 'age', 'salary', 'experience_years', 'department', 'city',
        'performance_score', 'bonus', 'working_hours', 'satisfaction_level'],
       dtype='str'),
 10)

In [120]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  1000 non-null   int64
 1   age                 900 non-null    float64
 2   salary              900 non-null    float64
 3   experience_years    900 non-null    float64
 4   department          1000 non-null   str
 5   city                1000 non-null   str
 6   performance_score   900 non-null    float64
 7   bonus               900 non-null    float64
 8   working_hours       1000 non-null   int64
 9   satisfaction_level  1000 non-null   float64
dtypes: float64(6), int64(2), str(2)
memory usage: 78.3 KB

In [121]:
df.describe()

,id,age,salary,experience_years,performance_score,bonus,working_hours,satisfaction_level
count,1000.000000,900.000000,900.000000,900.000000,900.000000,900.000000,1000.000000,1000.000000
mean,500.500000,43.650000,85370.073333,19.405556,2.931056,24817.851111,44.455000,0.494450
std,288.819436,15.028662,38357.305194,11.376506,1.155847,14738.407745,8.656264,0.290926
min,1.000000,18.000000,20060.000000,0.000000,1.000000,60.000000,30.000000,0.000000
25%,250.750000,31.000000,52262.250000,10.000000,1.910000,11701.000000,37.000000,0.240000
50%,500.500000,44.000000,84772.000000,19.500000,2.910000,24551.500000,44.000000,0.500000
75%,750.250000,56.000000,119105.500000,29.000000,3.932500,37707.250000,52.000000,0.730000
max,1000.000000,69.000000,149972.000000,39.000000,5.000000,49839.000000,59.000000,1.000000

In [122]:
new_df = df[["id", "age", "salary"]]
new_df

       id   age    salary
0       1  56.0  125186.0
1       2  69.0   54674.0
2       3  46.0   55854.0
3       4  32.0   66271.0
4       5  60.0   93688.0
..    ...   ...       ...
995   996  60.0  145991.0
996   997   NaN   29516.0
997   998  62.0  132863.0
998   999  35.0  135005.0
999  1000  55.0   22396.0

[1000 rows x 3 columns]

In [123]:
df.head(100)

,id,age,salary,experience_years,department,city,performance_score,bonus,working_hours,satisfaction_level
0,1,56.0,125186.0,2.0,Finance,Bangalore,2.69,18771.0,56,0.69
1,2,69.0,54674.0,39.0,HR,Delhi,1.34,NaN,51,0.28
2,3,46.0,55854.0,33.0,Sales,Pune,3.43,42330.0,45,0.69
3,4,32.0,66271.0,39.0,HR,Mumbai,4.52,29320.0,30,0.31
4,5,60.0,93688.0,26.0,Marketing,Delhi,4.53,4340.0,41,0.76
...,...,...,...,...,...,...,...,...,...,...
95,96,42.0,123864.0,34.0,IT,Bangalore,2.63,6297.0,58,0.69
96,97,NaN,73441.0,12.0,Finance,Pune,2.31,27856.0,33,0.23
97,98,58.0,NaN,38.0,Finance,Delhi,NaN,NaN,37,0.13
98,99,46.0,NaN,14.0,Finance,Bangalore,NaN,8334.0,45,0.89
99,100,32.0,99239.0,28.0,IT,Ahmedabad,1.50,24162.0,50,0.28

In [124]:
df.tail(10)

,id,age,salary,experience_years,department,city,performance_score,bonus,working_hours,satisfaction_level
990,991,24.0,NaN,33.0,Finance,Pune,3.30,37388.0,46,0.70
991,992,20.0,105956.0,19.0,HR,Ahmedabad,1.65,16195.0,40,0.09
992,993,64.0,106988.0,10.0,Finance,Mumbai,2.89,27689.0,57,0.50
993,994,40.0,65648.0,15.0,HR,Bangalore,3.21,11154.0,57,0.26
994,995,63.0,123537.0,30.0,IT,Mumbai,3.28,39121.0,37,0.72
995,996,60.0,145991.0,5.0,Finance,Delhi,1.84,29412.0,52,0.19
996,997,NaN,29516.0,18.0,Finance,Bangalore,3.97,21341.0,58,0.89
997,998,62.0,132863.0,36.0,IT,Delhi,1.10,32018.0,34,0.43
998,999,35.0,135005.0,3.0,Finance,Bangalore,2.42,9145.0,39,0.20
999,1000,55.0,22396.0,3.0,HR,Pune,4.12,42262.0,36,0.44

In [125]:
df.isna().sum()

id                      0
age                   100
salary                100
experience_years      100
department              0
city                    0
performance_score     100
bonus                 100
working_hours           0
satisfaction_level      0
dtype: int64

In [126]:
df["age"].isna().sum()

np.int64(100)

In [127]:
df.notna().sum()

id                    1000
age                    900
salary                 900
experience_years       900
department            1000
city                  1000
performance_score      900
bonus                  900
working_hours         1000
satisfaction_level    1000
dtype: int64

In [128]:
df2 = pd.read_csv("./dataset/indian movies.csv")
df2

,ID,Movie Name,Year,Timing(min),Rating(10),Votes,Genre,Language
0,tt0398974,Dr. Shaitan,1960,-,-,-,-,hindi
1,tt1702558,Nadir Khan,1968,-,-,-,-,urdu
2,tt0493437,Apna Sapna Money Money,2006,134 min,5.3,"1,892","Comedy, Musical, Romance",hindi
3,tt0273405,Aag Aur Sholay,1987,-,2.2,20,-,urdu
4,tt0049595,Parivar,1956,-,7.4,21,"Comedy, Drama, Family",hindi
...,...,...,...,...,...,...,...,...
50597,tt2784720,Sulagte Armaan,1984,-,-,-,Drama,hindi
50598,tt0315201,Aranya,1971,107 min,-,-,Drama,assamese
50599,tt0270221,Balayogini,1936,120 min,-,-,-,telugu
50600,tt0388697,Alajadi,1990,133 min,-,-,Drama,telugu
50601,tt14143738,KA-99 B-333,2009,-,-,-,Drama,kannada

In [129]:
df2.isna().sum()

ID                0
Movie Name        0
Year           1561
Timing(min)       0
Rating(10)        0
Votes             0
Genre             0
Language          0
dtype: int64

In [130]:
a = df2.drop(columns=["Year"])
a

,ID,Movie Name,Timing(min),Rating(10),Votes,Genre,Language
0,tt0398974,Dr. Shaitan,-,-,-,-,hindi
1,tt1702558,Nadir Khan,-,-,-,-,urdu
2,tt0493437,Apna Sapna Money Money,134 min,5.3,"1,892","Comedy, Musical, Romance",hindi
3,tt0273405,Aag Aur Sholay,-,2.2,20,-,urdu
4,tt0049595,Parivar,-,7.4,21,"Comedy, Drama, Family",hindi
...,...,...,...,...,...,...,...
50597,tt2784720,Sulagte Armaan,-,-,-,Drama,hindi
50598,tt0315201,Aranya,107 min,-,-,Drama,assamese
50599,tt0270221,Balayogini,120 min,-,-,-,telugu
50600,tt0388697,Alajadi,133 min,-,-,Drama,telugu
50601,tt14143738,KA-99 B-333,-,-,-,Drama,kannada

In [131]:
# a = df2.drop(columns=["Year"], inplace=True)
# a

In [132]:
# df2

In [133]:
df2.isna().sum()

ID                0
Movie Name        0
Year           1561
Timing(min)       0
Rating(10)        0
Votes             0
Genre             0
Language          0
dtype: int64

In [134]:
df2["Year"] = df2["Year"].bfill(inplace=True)
# b.isna().sum()

C:\Users\tapan\AppData\Local\Temp\ipykernel_6356\2974081589.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df2["Year"] = df2["Year"].bfill(inplace=True)

In [135]:
df2.isna().sum()

ID             0
Movie Name     0
Year           0
Timing(min)    0
Rating(10)     0
Votes          0
Genre          0
Language       0
dtype: int64

In [136]:
# c = df2["Year"].fillna(method='ffill')
# c.isna().sum()

In [ ]:
df2

,ID,Movie Name,Year,Timing(min),Rating(10),Votes,Genre,Language
0,tt0398974,Dr. Shaitan,1960,-,-,-,-,hindi
1,tt1702558,Nadir Khan,1968,-,-,-,-,urdu
2,tt0493437,Apna Sapna Money Money,2006,134 min,5.3,"1,892","Comedy, Musical, Romance",hindi
3,tt0273405,Aag Aur Sholay,1987,-,2.2,20,-,urdu
4,tt0049595,Parivar,1956,-,7.4,21,"Comedy, Drama, Family",hindi
...,...,...,...,...,...,...,...,...
50597,tt2784720,Sulagte Armaan,1984,-,-,-,Drama,hindi
50598,tt0315201,Aranya,1971,107 min,-,-,Drama,assamese
50599,tt0270221,Balayogini,1936,120 min,-,-,-,telugu
50600,tt0388697,Alajadi,1990,133 min,-,-,Drama,telugu
50601,tt14143738,KA-99 B-333,2009,-,-,-,Drama,kannada

In [138]:
df2["Year"] = df2["Year"].astype(int)

ValueError: invalid literal for int() with base 10: '2018 Video'

In [ ]:
df["age"] = df["age"].fillna(df["age"].mean(), inplace=True)
a

C:\Users\tapan\AppData\Local\Temp\ipykernel_6356\3519081638.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["age"] = df["age"].fillna(df["age"].mean(), inplace=True)

0      56.00
1      69.00
2      46.00
3      32.00
4      60.00
       ...
995    60.00
996    43.65
997    62.00
998    35.00
999    55.00
Name: age, Length: 1000, dtype: float64

In [ ]:
df.isna().sum()

id                      0
age                     0
salary                100
experience_years      100
department              0
city                    0
performance_score     100
bonus                 100
working_hours           0
satisfaction_level      0
dtype: int64

In [ ]:
df["age"].describe()

count    1000.000000
mean       43.650000
std        14.256648
min        18.000000
25%        33.000000
50%        43.650000
75%        54.000000
max        69.000000
Name: age, dtype: float64

In [ ]:
it = df[df["department"] == "IT"]
it.count()

id                    206
age                   206
salary                186
experience_years      190
department            206
city                  206
performance_score     184
bonus                 193
working_hours         206
satisfaction_level    206
dtype: int64

In [ ]:
df.sort_values(by="salary", ascending=False).head(3)

,id,age,salary,experience_years,department,city,performance_score,bonus,working_hours,satisfaction_level
868,869,47.0,149972.0,31.0,Marketing,Bangalore,3.50,2244.0,31,0.63
460,461,25.0,149948.0,5.0,Sales,Bangalore,NaN,44462.0,43,0.03
72,73,21.0,149922.0,25.0,Sales,Ahmedabad,4.29,5753.0,35,0.45

In [ ]:
df.loc[2:5]

,id,age,salary,experience_years,department,city,performance_score,bonus,working_hours,satisfaction_level
2,3,46.0,55854.0,33.0,Sales,Pune,3.43,42330.0,45,0.69
3,4,32.0,66271.0,39.0,HR,Mumbai,4.52,29320.0,30,0.31
4,5,60.0,93688.0,26.0,Marketing,Delhi,4.53,4340.0,41,0.76
5,6,25.0,NaN,NaN,Marketing,Ahmedabad,3.64,34924.0,53,0.62

In [ ]:
df.iloc[2:500, 3:6]

     experience_years department       city
2                33.0      Sales       Pune
3                39.0         HR     Mumbai
4                26.0  Marketing      Delhi
5                 NaN  Marketing  Ahmedabad
6                32.0  Marketing     Mumbai
..                ...        ...        ...
495              15.0      Sales     Mumbai
496              35.0         IT  Ahmedabad
497              29.0  Marketing       Pune
498              17.0      Sales  Bangalore
499               1.0      Sales  Ahmedabad

[498 rows x 3 columns]

In [144]:
# df["salary"].dropna()
# df["salary"].dropna(inplace=True)
df.dropna(subset=["salary"],inplace=True)

In [145]:
df.isna().sum()

id                     0
age                   93
salary                 0
experience_years      87
department             0
city                   0
performance_score     88
bonus                 94
working_hours          0
satisfaction_level     0
dtype: int64

In [146]:
df.shape

(900, 10)