In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("./dataset/employee_dataset.csv")
df.head()

,id,age,salary,experience_years,department,city,performance_score,bonus,working_hours,satisfaction_level
0,1,56.0,125186.0,2.0,Finance,Bangalore,2.69,18771.0,56,0.69
1,2,69.0,54674.0,39.0,HR,Delhi,1.34,NaN,51,0.28
2,3,46.0,55854.0,33.0,Sales,Pune,3.43,42330.0,45,0.69
3,4,32.0,66271.0,39.0,HR,Mumbai,4.52,29320.0,30,0.31
4,5,60.0,93688.0,26.0,Marketing,Delhi,4.53,4340.0,41,0.76

In [7]:
df["salary_bonus"] = (df["salary"] * 10) / 100
df.head()

,id,age,salary,experience_years,department,city,performance_score,bonus,working_hours,satisfaction_level,salary_bonus
0,1,56.0,125186.0,2.0,Finance,Bangalore,2.69,18771.0,56,0.69,12518.6
1,2,69.0,54674.0,39.0,HR,Delhi,1.34,NaN,51,0.28,5467.4
2,3,46.0,55854.0,33.0,Sales,Pune,3.43,42330.0,45,0.69,5585.4
3,4,32.0,66271.0,39.0,HR,Mumbai,4.52,29320.0,30,0.31,6627.1
4,5,60.0,93688.0,26.0,Marketing,Delhi,4.53,4340.0,41,0.76,9368.8

In [7]:
df["city_deparment"] = df["city"] + "-" + df["department"]
df.head()

,id,age,salary,experience_years,department,city,performance_score,bonus,working_hours,satisfaction_level,salary_bonus,city_deparment
0,1,56.0,125186.0,2.0,Finance,Bangalore,2.69,18771.0,56,0.69,12518.6,Bangalore-Finance
1,2,69.0,54674.0,39.0,HR,Delhi,1.34,NaN,51,0.28,5467.4,Delhi-HR
2,3,46.0,55854.0,33.0,Sales,Pune,3.43,42330.0,45,0.69,5585.4,Pune-Sales
3,4,32.0,66271.0,39.0,HR,Mumbai,4.52,29320.0,30,0.31,6627.1,Mumbai-HR
4,5,60.0,93688.0,26.0,Marketing,Delhi,4.53,4340.0,41,0.76,9368.8,Delhi-Marketing

In [ ]:
def salary_category(x):

    if x >= 100000:
        return "High"
    
    elif x >= 50000:
        return "Medium"
    
    elif x >= 20000:
        return "Low"


df["salary_category"] = df["salary"].apply(salary_category)
df

,id,age,salary,experience_years,department,city,performance_score,bonus,working_hours,satisfaction_level,salary_bonus,city_deparment,salary_category
0,1,56.0,125186.0,2.0,Finance,Bangalore,2.69,18771.0,56,0.69,12518.6,Bangalore-Finance,High
1,2,69.0,54674.0,39.0,HR,Delhi,1.34,NaN,51,0.28,5467.4,Delhi-HR,Medium
2,3,46.0,55854.0,33.0,Sales,Pune,3.43,42330.0,45,0.69,5585.4,Pune-Sales,Medium
3,4,32.0,66271.0,39.0,HR,Mumbai,4.52,29320.0,30,0.31,6627.1,Mumbai-HR,Medium
4,5,60.0,93688.0,26.0,Marketing,Delhi,4.53,4340.0,41,0.76,9368.8,Delhi-Marketing,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,60.0,145991.0,5.0,Finance,Delhi,1.84,29412.0,52,0.19,14599.1,Delhi-Finance,High
996,997,NaN,29516.0,18.0,Finance,Bangalore,3.97,21341.0,58,0.89,2951.6,Bangalore-Finance,Low
997,998,62.0,132863.0,36.0,IT,Delhi,1.10,32018.0,34,0.43,13286.3,Delhi-IT,High
998,999,35.0,135005.0,3.0,Finance,Bangalore,2.42,9145.0,39,0.20,13500.5,Bangalore-Finance,High
999,1000,55.0,22396.0,3.0,HR,Pune,4.12,42262.0,36,0.44,2239.6,Pune-HR,Low

In [9]:
df["salary"].min(), df["salary"].max()

(np.float64(20060.0), np.float64(149972.0))

In [21]:
df.groupby("salary_category")["salary_category"].count()

salary_category
High      345
Low       215
Medium    340
Name: salary_category, dtype: int64

In [23]:
df.groupby(["salary_category", "city"])["salary_category"].count()

salary_category  city
High             Ahmedabad    66
                 Bangalore    59
                 Delhi        75
                 Mumbai       81
                 Pune         64
Low              Ahmedabad    40
                 Bangalore    46
                 Delhi        45
                 Mumbai       39
                 Pune         45
Medium           Ahmedabad    72
                 Bangalore    64
                 Delhi        75
                 Mumbai       55
                 Pune         74
Name: salary_category, dtype: int64

In [31]:
df.to_csv("upgraded_employee_dataset.csv")

In [29]:
df.to_excel("upgraded_employee_dataset.xlsx")

In [30]:
df.to_json("upgraded_employee_dataset.json")