In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./dataset/payments.csv")
df.head()

     name gender  amount month       city payment_method     category
0   Aarav      M  1200.0   Jan  Ahmedabad            UPI         Food
1  Vivaan      M  1500.0   Jan     Mumbai           Card     Shopping
2  Aditya      M     NaN   Jan      Delhi           Cash        Bills
3  Vihaan      M  1100.0   Jan       Pune            UPI    Transport
4   Arjun      M  2000.0   Jan  Bangalore           Card  Electronics

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            99 non-null     str
 1   gender          100 non-null    str
 2   amount          83 non-null     float64
 3   month           100 non-null    str
 4   city            100 non-null    str
 5   payment_method  100 non-null    str
 6   category        100 non-null    str
dtypes: float64(1), str(6)
memory usage: 5.6 KB

In [30]:
df2 = df[["city", "amount", "month", "payment_method", "gender"]]
df2.head()

        city  amount month payment_method gender
0  Ahmedabad  1200.0   Jan            UPI      M
1     Mumbai  1500.0   Jan           Card      M
2      Delhi     NaN   Jan           Cash      M
3       Pune  1100.0   Jan            UPI      M
4  Bangalore  2000.0   Jan           Card      M

In [31]:
df2.pivot_table(index="month", values="amount", columns="city", aggfunc="sum")

city   Ahmedabad  Bangalore   Delhi  Hyderabad  Mumbai    Pune
month
Apr       1480.0     2300.0  3100.0        0.0  3150.0  3350.0
Aug       1550.0     2700.0  3100.0     1350.0  3550.0  3950.0
Feb       2830.0     2100.0  3100.0     1650.0     0.0  3100.0
Jan       1200.0     2000.0  1300.0     1700.0  2900.0  3000.0
Jul       2880.0     2600.0  3100.0     1400.0     0.0  3800.0
Jun       2850.0        0.0  3100.0     1450.0  3350.0  3650.0
Mar       2800.0     2200.0  1700.0     1600.0  3050.0  2000.0
May       2850.0     2400.0  1500.0     1500.0  3250.0  1300.0
Oct       2950.0     2900.0  1350.0     1250.0  3750.0  2700.0
Sep       2920.0     2800.0  1700.0     1300.0  3650.0  4100.0

In [32]:
df.groupby(["city"])["amount"].sum()

city
Ahmedabad    24310.0
Bangalore    22000.0
Delhi        23050.0
Hyderabad    13200.0
Mumbai       26650.0
Pune         30950.0
Name: amount, dtype: float64

In [35]:
df.pivot_table(index={"month", "payment_method"}, values=["amount", "category"], columns=["city", "gender"], aggfunc="sum")

                        amount                                            \
city                 Ahmedabad         Bangalore           Delhi
gender                       F       M         F       M       F       M
month payment_method
Apr   Card              1480.0     NaN    2300.0     NaN     NaN     NaN
      Cash                 NaN     NaN       NaN     NaN  1450.0     NaN
      UPI                  0.0     NaN       NaN     NaN  1650.0     NaN
Aug   Card                 0.0     NaN    2700.0     NaN     NaN     NaN
      Cash                 NaN     NaN       NaN     NaN  1650.0     NaN
      UPI               1550.0     NaN       NaN     NaN  1450.0     NaN
Feb   Card              1580.0     NaN    2100.0     NaN     NaN     NaN
      Cash                 NaN     NaN       NaN     NaN  1350.0     NaN
      UPI               1250.0     NaN       NaN     NaN  1750.0     NaN
Jan   Card                 NaN     NaN       NaN  2000.0     NaN     NaN
      Cash                 NaN     0.0       NaN     NaN     NaN     0.0
      UPI                  NaN  1200.0       NaN     NaN     NaN  1300.0
Jul   Card                 NaN  1380.0       NaN  2600.0     NaN     NaN
      Cash                 NaN     NaN       NaN     NaN     NaN  1600.0
      UPI                  NaN  1500.0       NaN     NaN     NaN  1500.0
Jun   Card              1400.0     NaN       0.0     NaN     NaN     NaN
      Cash                 NaN     NaN       NaN     NaN  1550.0     NaN
      UPI               1450.0     NaN       NaN     NaN  1550.0     NaN
Mar   Card                 NaN  1500.0       NaN  2200.0     NaN     NaN
      Cash                 NaN     NaN       NaN     NaN     NaN     0.0
      UPI                  NaN  1300.0       NaN     NaN     NaN  1700.0
May   Card                 NaN  1450.0       NaN  2400.0     NaN     NaN
      Cash                 NaN     NaN       NaN     NaN     NaN  1500.0
      UPI                  NaN  1400.0       NaN     NaN     NaN     0.0
Oct   Card              1300.0     NaN    2900.0     NaN     NaN     NaN
      Cash                 NaN     NaN       NaN     NaN     0.0     NaN
      UPI               1650.0     NaN       NaN     NaN  1350.0     NaN
Sep   Card                 NaN  1320.0       NaN  2800.0     NaN     NaN
      Cash                 NaN     NaN       NaN     NaN     NaN  1700.0
      UPI                  NaN  1600.0       NaN     NaN     NaN     0.0

                                                        ...     category  \
city                 Hyderabad          Mumbai          ...    Bangalore
gender                       F       M       F       M  ...            M
month payment_method                                    ...
Apr   Card                 NaN     NaN  1650.0     NaN  ...          NaN
      Cash                 NaN     NaN     NaN     NaN  ...          NaN
      UPI                  0.0     NaN  1500.0     NaN  ...          NaN
Aug   Card                 NaN     NaN  1850.0     NaN  ...          NaN
      Cash                 NaN     NaN     NaN     NaN  ...          NaN
      UPI               1350.0     NaN  1700.0     NaN  ...          NaN
Feb   Card                 NaN     NaN     0.0     NaN  ...          NaN
      Cash                 NaN     NaN     NaN     NaN  ...          NaN
      UPI               1650.0     NaN     0.0     NaN  ...          NaN
Jan   Card                 NaN     NaN     NaN  2900.0  ...  Electronics
      Cash                 NaN     NaN     NaN     NaN  ...          NaN
      UPI                  NaN  1700.0     NaN     NaN  ...          NaN
Jul   Card                 NaN     NaN     NaN     0.0  ...  Electronics
      Cash                 NaN     NaN     NaN     NaN  ...          NaN
      UPI                  NaN  1400.0     NaN     0.0  ...          NaN
Jun   Card                 NaN     NaN  1750.0     NaN  ...          NaN
      Cash                 NaN     NaN     NaN     NaN  ...          NaN
      UPI               1450.0     NaN  1600.0     NaN  ...          NaN
Mar   Card                 NaN     NaN     NaN  1600.0  ...  Electronics
      Cash                 NaN     NaN     NaN     NaN  ...          NaN
      UPI                  NaN  1600.0     NaN  1450.0  ...          NaN
May   Card                 NaN     NaN     NaN  1700.0  ...  Electronics
      Cash                 NaN     NaN     NaN     NaN  ...          NaN
      UPI                  NaN  1500.0     NaN  1550.0  ...          NaN
Oct   Card                 NaN     NaN  1950.0     NaN  ...          NaN
      Cash                 NaN     NaN     NaN     NaN  ...          NaN
      UPI               1250.0     NaN  1800.0     NaN  ...          NaN
Sep   Card                 NaN     NaN     NaN  1900.0  ...  Electronics
      Cash                 NaN     NaN     NaN     NaN  ...          NaN
      UPI                  NaN  1300.0     NaN  1750.0  ...          NaN

                                                                   \
city                  Delhi            Hyderabad           Mumbai
gender                    F          M         F     M          F
month payment_method
Apr   Card              NaN        NaN       NaN   NaN   Shopping
      Cash            Bills        NaN       NaN   NaN        NaN
      UPI             Bills        NaN      Food   NaN  Transport
Aug   Card              NaN        NaN       NaN   NaN   Shopping
      Cash            Bills        NaN       NaN   NaN        NaN
      UPI             Bills        NaN      Food   NaN  Transport
Feb   Card              NaN        NaN       NaN   NaN   Shopping
      Cash            Bills        NaN       NaN   NaN        NaN
      UPI             Bills        NaN      Food   NaN  Transport
Jan   Card              NaN        NaN       NaN   NaN        NaN
      Cash              NaN      Bills       NaN   NaN        NaN
      UPI               NaN  Transport       NaN  Food        NaN
Jul   Card              NaN        NaN       NaN   NaN        NaN
      Cash              NaN      Bills       NaN   NaN        NaN
      UPI               NaN      Bills       NaN  Food        NaN
Jun   Card              NaN        NaN       NaN   NaN   Shopping
      Cash            Bills        NaN       NaN   NaN        NaN
      UPI             Bills        NaN      Food   NaN  Transport
Mar   Card              NaN        NaN       NaN   NaN        NaN
      Cash              NaN      Bills       NaN   NaN        NaN
      UPI               NaN      Bills       NaN  Food        NaN
May   Card              NaN        NaN       NaN   NaN        NaN
      Cash              NaN      Bills       NaN   NaN        NaN
      UPI               NaN      Bills       NaN  Food        NaN
Oct   Card              NaN        NaN       NaN   NaN   Shopping
      Cash            Bills        NaN       NaN   NaN        NaN
      UPI             Bills        NaN      Food   NaN  Transport
Sep   Card              NaN        NaN       NaN   NaN        NaN
      Cash              NaN      Bills       NaN   NaN        NaN
      UPI               NaN      Bills       NaN  Food        NaN


city                                           Pune
gender                               M                         F            M
month payment_method
Apr   Card                         NaN          NaN  Electronics          NaN
      Cash                         NaN          NaN    Transport          NaN
      UPI                          NaN          NaN          NaN          NaN
Aug   Card                         NaN          NaN  Electronics          NaN
      Cash                         NaN          NaN    Transport          NaN
      UPI                          NaN          NaN          NaN          NaN
Feb   Card                         NaN          NaN  Electronics          NaN
      Cash                         NaN          NaN    Transport          NaN
      UPI                          NaN          NaN          NaN          NaN
Jan   Card            ShoppingShopping          NaN          NaN  Electronics
      Cash                         NaN          NaN          NaN          NaN
      UPI                          NaN          NaN          NaN    Transport
Jul   Card                    Shopping          NaN          NaN  Electronics
      Cash                         NaN          NaN          NaN    Transport
      UPI                    Transport          NaN          NaN          NaN
Jun   Card                         NaN          NaN  Electronics          NaN
      Cash                         NaN          NaN    Transport          NaN
      UPI                          NaN          NaN          NaN          NaN
Mar   Card                    Shopping          NaN          NaN  Electronics
      Cash                         NaN          NaN          NaN    Transport
      UPI                    Transport          NaN          NaN          NaN
May   Card                    Shopping          NaN          NaN  Electronics
      Cash                         NaN          NaN          NaN    Transport
      UPI                    Transport          NaN          NaN          NaN
Oct   Card                         NaN  Electronics          NaN          NaN
      Cash                         NaN          NaN    Transport          NaN
      UPI                          NaN          NaN          NaN          NaN
Sep   Card                    Shopping          NaN          NaN  Electronics
      Cash                         NaN          NaN          NaN    Transport
      UPI                    Transport          NaN          NaN          NaN

[30 rows x 26 columns]