In [9]:
import pandas as pd

In [26]:
all_orders = pd.read_csv("./dataset/all_orders.csv")
customers = pd.read_csv("./dataset/customers.csv")

In [11]:
all_orders.head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped

In [12]:
customers.head()

  customer_id customer_name gender       city        state signup_date
0        C001   Aarav Patel      M  Ahmedabad      Gujarat  2024-01-12
1        C002   Diya Sharma      F     Mumbai  Maharashtra  2024-02-18
2        C003  Vivaan Mehta      M      Surat      Gujarat  2024-03-05
3        C004  Ananya Verma      F      Delhi        Delhi  2024-01-28
4        C005    Krish Shah      M     Rajkot      Gujarat  2024-04-10

In [13]:
merged_df = pd.merge(customers, all_orders)
merged_df.head()

,customer_id,customer_name,gender,city,state,signup_date,order_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O002,P003,2025-01-07,2,5000,UPI,Delivered
2,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O005,P010,2025-01-10,1,3200,UPI,Shipped
3,C002,Diya Sharma,F,Mumbai,Maharashtra,2024-02-18,O003,P002,2025-01-08,1,28000,Debit Card,Cancelled
4,C002,Diya Sharma,F,Mumbai,Maharashtra,2024-02-18,O009,P007,2025-01-13,1,14500,Debit Card,Returned

In [17]:
merged_df = pd.merge(customers, all_orders, how="left_anti")
merged_df

,customer_id,customer_name,gender,city,state,signup_date,order_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
10,C008,Kavya Nair,F,Bengaluru,Karnataka,2024-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,C009,Arjun Singh,M,Jaipur,Rajasthan,2024-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,C010,Meera Kapoor,F,Chandigarh,Chandigarh,2024-02-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,C011,Yash Trivedi,M,Ahmedabad,Gujarat,2024-03-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,C012,Simran Kaur,F,Ludhiana,Punjab,2024-04-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,C013,Dev Malhotra,M,Delhi,Delhi,2024-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,C014,Riya Pandey,F,Patna,Bihar,2024-05-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,C015,Aditya Rao,M,Hyderabad,Telangana,2024-03-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,C016,Priya Iyer,F,Chennai,Tamil Nadu,2024-02-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,C017,Karan Chauhan,M,Indore,Madhya Pradesh,2024-04-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,C018,Neha Soni,F,Udaipur,Rajasthan,2024-05-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,C019,Siddharth Jain,M,Nagpur,Maharashtra,2024-01-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,C020,Pooja Mishra,F,Kanpur,Uttar Pradesh,2024-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Append

In [20]:
orders1 = pd.read_csv("./dataset/orders.csv")
orders2 = pd.read_csv("./dataset/orders2.csv")

In [23]:
append_df = pd.concat([orders1, orders2]).reset_index(drop=True)
append_df

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped
5,O006,C004,P004,2025-01-11,2,3600,Credit Card,Delivered
6,O007,C005,P006,2025-01-11,1,22000,Net Banking,Pending
7,O008,C006,P009,2025-01-12,2,9000,UPI,Delivered
8,O009,C002,P007,2025-01-13,1,14500,Debit Card,Returned
9,O010,C007,P012,2025-01-13,3,4500,Cash,Delivered
10,O011,C008,P015,2025-01-14,5,3500,UPI,Delivered
11,O012,C009,P014,2025-01-15,1,5200,Credit Card,Cancelled
12,O013,C010,P011,2025-01-15,1,55000,Net Banking,Delivered
13,O014,C003,P013,2025-01-16,2,5600,UPI,Shipped
14,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered
15,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending
16,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered
17,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered
18,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped
19,O020,C001,P005,2025-01-19,4,3600,UPI,Delivered
20,O021,C002,P003,2025-01-19,1,2500,Cash,Delivered
21,O022,C003,P002,2025-01-20,1,28000,Credit Card,Delivered
22,O023,C004,P009,2025-01-20,2,9000,UPI,Pending
23,O024,C005,P008,2025-01-21,1,12000,Debit Card,Delivered
24,O025,C006,P010,2025-01-21,3,9600,Credit Card,Returned
25,O026,C007,P001,2025-01-22,1,65000,Net Banking,Delivered
26,O027,C008,P004,2025-01-22,2,3600,Cash,Delivered
27,O028,C009,P015,2025-01-23,10,7000,UPI,Delivered
28,O029,C010,P012,2025-01-23,4,6000,UPI,Cancelled
29,O030,C001,P014,2025-01-24,1,5200,Credit Card,Delivered

In [24]:
append_df.to_csv("orders3.csv")