In [1]:
import pandas as pd
import numpy as np

#### Series

In [2]:
age = pd.Series([1,2,3,4,5,6])

print(age)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
name = pd.Series(["abc", "xyz", "pqr", "sdf"])

name

0    abc
1    xyz
2    pqr
3    sdf
dtype: str

#### Dataframe

In [4]:
d = {"name": ["abc", "xyz", "pqr", None], "age": [10, 40, None, 30]}

df = pd.DataFrame(d)

df

  name   age
0  abc  10.0
1  xyz  40.0
2  pqr   NaN
3  NaN  30.0

In [5]:
d2 = {
    "name" : name,
    "age" : age
}

df2 = pd.DataFrame(d2, index=[6,5,4,3,2,1])

df2

  name  age
6  NaN  NaN
5  NaN  6.0
4  NaN  5.0
3  sdf  4.0
2  pqr  3.0
1  xyz  2.0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      float64
dtypes: float64(1), str(1)
memory usage: 196.0 bytes

In [7]:
n_df = df2.set_index(np.array([6,5,4,3,2,1]))

n_df

  name  age
6  NaN  NaN
5  NaN  6.0
4  NaN  5.0
3  sdf  4.0
2  pqr  3.0
1  xyz  2.0

In [8]:
df2.info()

<class 'pandas.DataFrame'>
Index: 6 entries, 6 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     5 non-null      float64
dtypes: float64(1), str(1)
memory usage: 144.0 bytes

df2.columns

In [9]:
age = df2["age"]

age

6    NaN
5    6.0
4    5.0
3    4.0
2    3.0
1    2.0
Name: age, dtype: float64

In [10]:
type(age), type(df2)

(pandas.Series, pandas.DataFrame)

#### Filter

In [11]:
fil = df2[(df2["age"] % 2 == 0)]

fil

  name  age
5  NaN  6.0
3  sdf  4.0
1  xyz  2.0

In [12]:
fil = df2[df2.isna().any(axis=1)]

fil

  name  age
6  NaN  NaN
5  NaN  6.0
4  NaN  5.0

In [13]:
fil = df2[df2["name"].isna()]

fil

  name  age
6  NaN  NaN
5  NaN  6.0
4  NaN  5.0

In [14]:
fil = df2[df2["name"].isna()].reset_index()

fil

   index name  age
0      6  NaN  NaN
1      5  NaN  6.0
2      4  NaN  5.0

In [15]:
fil = df2[df2["name"].isna()].reset_index(drop=True)

fil

  name  age
0  NaN  NaN
1  NaN  6.0
2  NaN  5.0