#### payments.csv

In [5]:
import pandas as pd

In [ ]:
df = pd.read_csv("./dataset/payments.csv")
df.head() # to show entire table

     name gender  amount month       city payment_method     category
0   Aarav      M  1200.0   Jan  Ahmedabad            UPI         Food
1  Vivaan      M  1500.0   Jan     Mumbai           Card     Shopping
2  Aditya      M     NaN   Jan      Delhi           Cash        Bills
3  Vihaan      M  1100.0   Jan       Pune            UPI    Transport
4   Arjun      M  2000.0   Jan  Bangalore           Card  Electronics

In [7]:
df.info() # must to know datatypes

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            99 non-null     str
 1   gender          100 non-null    str
 2   amount          83 non-null     float64
 3   month           100 non-null    str
 4   city            100 non-null    str
 5   payment_method  100 non-null    str
 6   category        100 non-null    str
dtypes: float64(1), str(6)
memory usage: 5.6 KB

In [8]:
df2 = df[["city", "amount", "month", "payment_method", "gender"]] # new df for pivot table
df2.head()

        city  amount month payment_method gender
0  Ahmedabad  1200.0   Jan            UPI      M
1     Mumbai  1500.0   Jan           Card      M
2      Delhi     NaN   Jan           Cash      M
3       Pune  1100.0   Jan            UPI      M
4  Bangalore  2000.0   Jan           Card      M

#### pivot table
#### index, vales and columns are must be specified in pivot table
#### values must be numeric data
#### index and columns can be categorical data
#### aggregation function is used to aggregate the values in pivot table

In [9]:
df2.pivot_table(index="month", values="amount", columns="city", aggfunc="sum")

city   Ahmedabad  Bangalore   Delhi  Hyderabad  Mumbai    Pune
month
Apr       1480.0     2300.0  3100.0        0.0  3150.0  3350.0
Aug       1550.0     2700.0  3100.0     1350.0  3550.0  3950.0
Feb       2830.0     2100.0  3100.0     1650.0     0.0  3100.0
Jan       1200.0     2000.0  1300.0     1700.0  2900.0  3000.0
Jul       2880.0     2600.0  3100.0     1400.0     0.0  3800.0
Jun       2850.0        0.0  3100.0     1450.0  3350.0  3650.0
Mar       2800.0     2200.0  1700.0     1600.0  3050.0  2000.0
May       2850.0     2400.0  1500.0     1500.0  3250.0  1300.0
Oct       2950.0     2900.0  1350.0     1250.0  3750.0  2700.0
Sep       2920.0     2800.0  1700.0     1300.0  3650.0  4100.0

In [10]:
df.groupby(["city"])["amount"].sum()

city
Ahmedabad    24310.0
Bangalore    22000.0
Delhi        23050.0
Hyderabad    13200.0
Mumbai       26650.0
Pune         30950.0
Name: amount, dtype: float64

In [11]:
df.pivot_table(index={"month", "payment_method"}, values=["amount", "category"], columns=["city", "gender"], aggfunc="sum")

                        amount                                            \
city                 Ahmedabad         Bangalore           Delhi
gender                       F       M         F       M       F       M
payment_method month
Card           Apr      1480.0     NaN    2300.0     NaN     NaN     NaN
               Aug         0.0     NaN    2700.0     NaN     NaN     NaN
               Feb      1580.0     NaN    2100.0     NaN     NaN     NaN
               Jan         NaN     NaN       NaN  2000.0     NaN     NaN
               Jul         NaN  1380.0       NaN  2600.0     NaN     NaN
               Jun      1400.0     NaN       0.0     NaN     NaN     NaN
               Mar         NaN  1500.0       NaN  2200.0     NaN     NaN
               May         NaN  1450.0       NaN  2400.0     NaN     NaN
               Oct      1300.0     NaN    2900.0     NaN     NaN     NaN
               Sep         NaN  1320.0       NaN  2800.0     NaN     NaN
Cash           Apr         NaN     NaN       NaN     NaN  1450.0     NaN
               Aug         NaN     NaN       NaN     NaN  1650.0     NaN
               Feb         NaN     NaN       NaN     NaN  1350.0     NaN
               Jan         NaN     0.0       NaN     NaN     NaN     0.0
               Jul         NaN     NaN       NaN     NaN     NaN  1600.0
               Jun         NaN     NaN       NaN     NaN  1550.0     NaN
               Mar         NaN     NaN       NaN     NaN     NaN     0.0
               May         NaN     NaN       NaN     NaN     NaN  1500.0
               Oct         NaN     NaN       NaN     NaN     0.0     NaN
               Sep         NaN     NaN       NaN     NaN     NaN  1700.0
UPI            Apr         0.0     NaN       NaN     NaN  1650.0     NaN
               Aug      1550.0     NaN       NaN     NaN  1450.0     NaN
               Feb      1250.0     NaN       NaN     NaN  1750.0     NaN
               Jan         NaN  1200.0       NaN     NaN     NaN  1300.0
               Jul         NaN  1500.0       NaN     NaN     NaN  1500.0
               Jun      1450.0     NaN       NaN     NaN  1550.0     NaN
               Mar         NaN  1300.0       NaN     NaN     NaN  1700.0
               May         NaN  1400.0       NaN     NaN     NaN     0.0
               Oct      1650.0     NaN       NaN     NaN  1350.0     NaN
               Sep         NaN  1600.0       NaN     NaN     NaN     0.0

                                                        ...     category  \
city                 Hyderabad          Mumbai          ...    Bangalore
gender                       F       M       F       M  ...            M
payment_method month                                    ...
Card           Apr         NaN     NaN  1650.0     NaN  ...          NaN
               Aug         NaN     NaN  1850.0     NaN  ...          NaN
               Feb         NaN     NaN     0.0     NaN  ...          NaN
               Jan         NaN     NaN     NaN  2900.0  ...  Electronics
               Jul         NaN     NaN     NaN     0.0  ...  Electronics
               Jun         NaN     NaN  1750.0     NaN  ...          NaN
               Mar         NaN     NaN     NaN  1600.0  ...  Electronics
               May         NaN     NaN     NaN  1700.0  ...  Electronics
               Oct         NaN     NaN  1950.0     NaN  ...          NaN
               Sep         NaN     NaN     NaN  1900.0  ...  Electronics
Cash           Apr         NaN     NaN     NaN     NaN  ...          NaN
               Aug         NaN     NaN     NaN     NaN  ...          NaN
               Feb         NaN     NaN     NaN     NaN  ...          NaN
               Jan         NaN     NaN     NaN     NaN  ...          NaN
               Jul         NaN     NaN     NaN     NaN  ...          NaN
               Jun         NaN     NaN     NaN     NaN  ...          NaN
               Mar         NaN     NaN     NaN     NaN  ...          NaN
               May         NaN     NaN     NaN     NaN  ...          NaN
               Oct         NaN     NaN     NaN     NaN  ...          NaN
               Sep         NaN     NaN     NaN     NaN  ...          NaN
UPI            Apr         0.0     NaN  1500.0     NaN  ...          NaN
               Aug      1350.0     NaN  1700.0     NaN  ...          NaN
               Feb      1650.0     NaN     0.0     NaN  ...          NaN
               Jan         NaN  1700.0     NaN     NaN  ...          NaN
               Jul         NaN  1400.0     NaN     0.0  ...          NaN
               Jun      1450.0     NaN  1600.0     NaN  ...          NaN
               Mar         NaN  1600.0     NaN  1450.0  ...          NaN
               May         NaN  1500.0     NaN  1550.0  ...          NaN
               Oct      1250.0     NaN  1800.0     NaN  ...          NaN
               Sep         NaN  1300.0     NaN  1750.0  ...          NaN

                                                                   \
city                  Delhi            Hyderabad           Mumbai
gender                    F          M         F     M          F
payment_method month
Card           Apr      NaN        NaN       NaN   NaN   Shopping
               Aug      NaN        NaN       NaN   NaN   Shopping
               Feb      NaN        NaN       NaN   NaN   Shopping
               Jan      NaN        NaN       NaN   NaN        NaN
               Jul      NaN        NaN       NaN   NaN        NaN
               Jun      NaN        NaN       NaN   NaN   Shopping
               Mar      NaN        NaN       NaN   NaN        NaN
               May      NaN        NaN       NaN   NaN        NaN
               Oct      NaN        NaN       NaN   NaN   Shopping
               Sep      NaN        NaN       NaN   NaN        NaN
Cash           Apr    Bills        NaN       NaN   NaN        NaN
               Aug    Bills        NaN       NaN   NaN        NaN
               Feb    Bills        NaN       NaN   NaN        NaN
               Jan      NaN      Bills       NaN   NaN        NaN
               Jul      NaN      Bills       NaN   NaN        NaN
               Jun    Bills        NaN       NaN   NaN        NaN
               Mar      NaN      Bills       NaN   NaN        NaN
               May      NaN      Bills       NaN   NaN        NaN
               Oct    Bills        NaN       NaN   NaN        NaN
               Sep      NaN      Bills       NaN   NaN        NaN
UPI            Apr    Bills        NaN      Food   NaN  Transport
               Aug    Bills        NaN      Food   NaN  Transport
               Feb    Bills        NaN      Food   NaN  Transport
               Jan      NaN  Transport       NaN  Food        NaN
               Jul      NaN      Bills       NaN  Food        NaN
               Jun    Bills        NaN      Food   NaN  Transport
               Mar      NaN      Bills       NaN  Food        NaN
               May      NaN      Bills       NaN  Food        NaN
               Oct    Bills        NaN      Food   NaN  Transport
               Sep      NaN      Bills       NaN  Food        NaN


city                                           Pune
gender                               M                         F            M
payment_method month
Card           Apr                 NaN          NaN  Electronics          NaN
               Aug                 NaN          NaN  Electronics          NaN
               Feb                 NaN          NaN  Electronics          NaN
               Jan    ShoppingShopping          NaN          NaN  Electronics
               Jul            Shopping          NaN          NaN  Electronics
               Jun                 NaN          NaN  Electronics          NaN
               Mar            Shopping          NaN          NaN  Electronics
               May            Shopping          NaN          NaN  Electronics
               Oct                 NaN  Electronics          NaN          NaN
               Sep            Shopping          NaN          NaN  Electronics
Cash           Apr                 NaN          NaN    Transport          NaN
               Aug                 NaN          NaN    Transport          NaN
               Feb                 NaN          NaN    Transport          NaN
               Jan                 NaN          NaN          NaN          NaN
               Jul                 NaN          NaN          NaN    Transport
               Jun                 NaN          NaN    Transport          NaN
               Mar                 NaN          NaN          NaN    Transport
               May                 NaN          NaN          NaN    Transport
               Oct                 NaN          NaN    Transport          NaN
               Sep                 NaN          NaN          NaN    Transport
UPI            Apr                 NaN          NaN          NaN          NaN
               Aug                 NaN          NaN          NaN          NaN
               Feb                 NaN          NaN          NaN          NaN
               Jan                 NaN          NaN          NaN    Transport
               Jul           Transport          NaN          NaN          NaN
               Jun                 NaN          NaN          NaN          NaN
               Mar           Transport          NaN          NaN          NaN
               May           Transport          NaN          NaN          NaN
               Oct                 NaN          NaN          NaN          NaN
               Sep           Transport          NaN          NaN          NaN

[30 rows x 26 columns]