In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("./dataset/pandas_full_practice.csv")
df.head()

In [ ]:
df.columns

df.shape

In [ ]:
df.isna().sum()

In [ ]:
df.groupby("gender")["salary"].sum().sort_values(ascending=False)

In [ ]:
df.groupby("department")["salary"].sum().sort_values(ascending=True)

In [ ]:
df.groupby(["gender", "department"])["salary"].sum().sort_values(ascending=False)

In [ ]:
df.groupby(["gender", "department"])["salary"].sum().sort_values(ascending=False)

#### Payments Data csv file = payments.csv

In [ ]:
import pandas as pd

payments = pd.read_csv("./dataset/payments.csv")
payments.head()

In [ ]:
payments.info()

payments.shape

In [8]:
df = payments.groupby(["city", "payment_method"])["amount"].sum().reset_index(name="transection")
df

         city payment_method  transection
0   Ahmedabad           Card      11410.0
1   Ahmedabad           Cash          0.0
2   Ahmedabad            UPI      12900.0
3   Bangalore           Card      22000.0
4       Delhi           Cash      10800.0
5       Delhi            UPI      12250.0
6   Hyderabad            UPI      13200.0
7      Mumbai           Card      15300.0
8      Mumbai            UPI      11350.0
9        Pune           Card      20450.0
10       Pune           Cash       9400.0
11       Pune            UPI       1100.0

In [11]:
df.pivot_table(index="city", columns="payment_method", values="transection", aggfunc="sum")

payment_method     Card     Cash      UPI
city
Ahmedabad       11410.0      0.0  12900.0
Bangalore       22000.0      NaN      NaN
Delhi               NaN  10800.0  12250.0
Hyderabad           NaN      NaN  13200.0
Mumbai          15300.0      NaN  11350.0
Pune            20450.0   9400.0   1100.0