In [1]:
import pandas as pd

#### Pandas Datetime

In [2]:
df = pd.read_csv("./dataset/sales_data.csv") # reads csv

df

,Order_ID,Date,Customer,Gender,Product,Category,Quantity,Price,Revenue
0,1001,05-01-2024,Amit,Male,Laptop,Electronics,1,55000,55000
1,1002,12-01-2024,Priya,Female,Chair,Furniture,2,3500,7000
2,1003,03-02-2024,Rahul,Male,Mobile,Electronics,3,18000,54000
3,1004,15-02-2024,Neha,Female,Table,Furniture,1,8500,8500
4,1005,08-03-2024,Vikram,Male,Headphones,Electronics,4,2500,10000
5,1006,20-03-2024,Anjali,Female,Sofa,Furniture,1,28000,28000
6,1007,02-04-2024,Rohan,Male,Monitor,Electronics,2,12000,24000
7,1008,18-04-2024,Kavya,Female,Desk,Furniture,1,9500,9500
8,1009,10-05-2024,Arjun,Male,Keyboard,Electronics,5,1500,7500
9,1010,25-05-2024,Meera,Female,Bookshelf,Furniture,2,6500,13000

In [3]:
df.dtypes # data types of columns in the table

Order_ID    int64
Date          str
Customer      str
Gender        str
Product       str
Category      str
Quantity    int64
Price       int64
Revenue     int64
dtype: object

In [4]:
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y") # it wont change the date formate because its in the standard ISO 8601 format

df

,Order_ID,Date,Customer,Gender,Product,Category,Quantity,Price,Revenue
0,1001,2024-01-05,Amit,Male,Laptop,Electronics,1,55000,55000
1,1002,2024-01-12,Priya,Female,Chair,Furniture,2,3500,7000
2,1003,2024-02-03,Rahul,Male,Mobile,Electronics,3,18000,54000
3,1004,2024-02-15,Neha,Female,Table,Furniture,1,8500,8500
4,1005,2024-03-08,Vikram,Male,Headphones,Electronics,4,2500,10000
5,1006,2024-03-20,Anjali,Female,Sofa,Furniture,1,28000,28000
6,1007,2024-04-02,Rohan,Male,Monitor,Electronics,2,12000,24000
7,1008,2024-04-18,Kavya,Female,Desk,Furniture,1,9500,9500
8,1009,2024-05-10,Arjun,Male,Keyboard,Electronics,5,1500,7500
9,1010,2024-05-25,Meera,Female,Bookshelf,Furniture,2,6500,13000

In [1]:
df["New Date Formate"] = df["Date"].dt.strftime("%d-%m-%Y") # it will change the date formate

df

# we can change any date formate after using ".strftime" function

NameError: name 'df' is not defined

In [15]:
df["month"] = df["Date"].dt.month # to show only month column

df

,Order_ID,Date,Customer,Gender,Product,Category,Quantity,Price,Revenue,Date2,month,new_date_format,New Date Formate
0,1001,2024-01-05,Amit,Male,Laptop,Electronics,1,55000,55000,05-01-2024,1,05-01-2024,05-01-2024
1,1002,2024-01-12,Priya,Female,Chair,Furniture,2,3500,7000,12-01-2024,1,12-01-2024,12-01-2024
2,1003,2024-02-03,Rahul,Male,Mobile,Electronics,3,18000,54000,03-02-2024,2,03-02-2024,03-02-2024
3,1004,2024-02-15,Neha,Female,Table,Furniture,1,8500,8500,15-02-2024,2,15-02-2024,15-02-2024
4,1005,2024-03-08,Vikram,Male,Headphones,Electronics,4,2500,10000,08-03-2024,3,08-03-2024,08-03-2024
5,1006,2024-03-20,Anjali,Female,Sofa,Furniture,1,28000,28000,20-03-2024,3,20-03-2024,20-03-2024
6,1007,2024-04-02,Rohan,Male,Monitor,Electronics,2,12000,24000,02-04-2024,4,02-04-2024,02-04-2024
7,1008,2024-04-18,Kavya,Female,Desk,Furniture,1,9500,9500,18-04-2024,4,18-04-2024,18-04-2024
8,1009,2024-05-10,Arjun,Male,Keyboard,Electronics,5,1500,7500,10-05-2024,5,10-05-2024,10-05-2024
9,1010,2024-05-25,Meera,Female,Bookshelf,Furniture,2,6500,13000,25-05-2024,5,25-05-2024,25-05-2024

In [16]:
df["new_date_format"] = df["Date"].dt.strftime("%d-%m-%Y") # to change the date formate

df

,Order_ID,Date,Customer,Gender,Product,Category,Quantity,Price,Revenue,Date2,month,new_date_format,New Date Formate
0,1001,2024-01-05,Amit,Male,Laptop,Electronics,1,55000,55000,05-01-2024,1,05-01-2024,05-01-2024
1,1002,2024-01-12,Priya,Female,Chair,Furniture,2,3500,7000,12-01-2024,1,12-01-2024,12-01-2024
2,1003,2024-02-03,Rahul,Male,Mobile,Electronics,3,18000,54000,03-02-2024,2,03-02-2024,03-02-2024
3,1004,2024-02-15,Neha,Female,Table,Furniture,1,8500,8500,15-02-2024,2,15-02-2024,15-02-2024
4,1005,2024-03-08,Vikram,Male,Headphones,Electronics,4,2500,10000,08-03-2024,3,08-03-2024,08-03-2024
5,1006,2024-03-20,Anjali,Female,Sofa,Furniture,1,28000,28000,20-03-2024,3,20-03-2024,20-03-2024
6,1007,2024-04-02,Rohan,Male,Monitor,Electronics,2,12000,24000,02-04-2024,4,02-04-2024,02-04-2024
7,1008,2024-04-18,Kavya,Female,Desk,Furniture,1,9500,9500,18-04-2024,4,18-04-2024,18-04-2024
8,1009,2024-05-10,Arjun,Male,Keyboard,Electronics,5,1500,7500,10-05-2024,5,10-05-2024,10-05-2024
9,1010,2024-05-25,Meera,Female,Bookshelf,Furniture,2,6500,13000,25-05-2024,5,25-05-2024,25-05-2024

In [8]:
# df["month2"] = df["new_date_format"].dt.month # it will give an error

# df

#### Pandas Query

In [17]:
df.query("Quantity >= 3") # query must be written in string aka "" (double quotes)

,Order_ID,Date,Customer,Gender,Product,Category,Quantity,Price,Revenue,Date2,month,new_date_format,New Date Formate
2,1003,2024-02-03,Rahul,Male,Mobile,Electronics,3,18000,54000,03-02-2024,2,03-02-2024,03-02-2024
4,1005,2024-03-08,Vikram,Male,Headphones,Electronics,4,2500,10000,08-03-2024,3,08-03-2024,08-03-2024
8,1009,2024-05-10,Arjun,Male,Keyboard,Electronics,5,1500,7500,10-05-2024,5,10-05-2024,10-05-2024

In [18]:
n = 3 # "n" is variable here

df.query("Quantity >= @n") # @ for variables

,Order_ID,Date,Customer,Gender,Product,Category,Quantity,Price,Revenue,Date2,month,new_date_format,New Date Formate
2,1003,2024-02-03,Rahul,Male,Mobile,Electronics,3,18000,54000,03-02-2024,2,03-02-2024,03-02-2024
4,1005,2024-03-08,Vikram,Male,Headphones,Electronics,4,2500,10000,08-03-2024,3,08-03-2024,08-03-2024
8,1009,2024-05-10,Arjun,Male,Keyboard,Electronics,5,1500,7500,10-05-2024,5,10-05-2024,10-05-2024

In [19]:
df.query("Product == 'Mobile'") # for a specific product

# here product name must be in '' (singe quotes)

,Order_ID,Date,Customer,Gender,Product,Category,Quantity,Price,Revenue,Date2,month,new_date_format,New Date Formate
2,1003,2024-02-03,Rahul,Male,Mobile,Electronics,3,18000,54000,03-02-2024,2,03-02-2024,03-02-2024

In [20]:
p = ["Mobile", "Keyboard"] # "p" is variable here

df.query("Product in @p")

,Order_ID,Date,Customer,Gender,Product,Category,Quantity,Price,Revenue,Date2,month,new_date_format,New Date Formate
2,1003,2024-02-03,Rahul,Male,Mobile,Electronics,3,18000,54000,03-02-2024,2,03-02-2024,03-02-2024
8,1009,2024-05-10,Arjun,Male,Keyboard,Electronics,5,1500,7500,10-05-2024,5,10-05-2024,10-05-2024

#### Pandas Crosstab

In [21]:
pd.crosstab(index=df["Gender"], columns=df["Product"], values=df["Price"], aggfunc="sum", margins=True, margins_name="Total")

# index # column name # values #aggfunc must to operate the data

# here margins for sum and margins name for rename the new column and row

# same as pivot table

Product,Bookshelf,Chair,Desk,Headphones,Keyboard,Laptop,Mobile,Monitor,Sofa,Table,Total
Gender,,,,,,,,,,,
Female,6500.0,3500.0,9500.0,NaN,NaN,NaN,NaN,NaN,28000.0,8500.0,56000
Male,NaN,NaN,NaN,2500.0,1500.0,55000.0,18000.0,12000.0,NaN,NaN,89000
Total,6500.0,3500.0,9500.0,2500.0,1500.0,55000.0,18000.0,12000.0,28000.0,8500.0,145000