#### 🟢 Part 1: Concat (Append) Questions

In [2]:
import pandas as pd

df1 = pd.read_csv("../../dataset/orders.csv")
df2 = pd.read_csv("../../dataset/orders2.csv")

In [3]:
df1.head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped

In [4]:
df2.head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered
1,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending
2,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered
3,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered
4,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped

In [5]:
# 1. Load orders.csv and orders2.csv

df1 = pd.read_csv("../../dataset/orders.csv")
df2 = pd.read_csv("../../dataset/orders2.csv")

print(df1.head())
print(df2.head())

  order_id customer_id product_id  order_date  quantity  total_amount  \
0     O001        C001       P001  2025-01-05         1         65000
1     O002        C001       P003  2025-01-07         2          5000
2     O003        C002       P002  2025-01-08         1         28000
3     O004        C003       P005  2025-01-08         3          2700
4     O005        C001       P010  2025-01-10         1          3200

  payment_mode order_status
0  Credit Card    Delivered
1          UPI    Delivered
2   Debit Card    Cancelled
3         Cash    Delivered
4          UPI      Shipped
  order_id customer_id product_id  order_date  quantity  total_amount  \
0     O015        C011       P016  2025-01-16         1          8500
1     O016        C012       P018  2025-01-17         1         42000
2     O017        C013       P017  2025-01-17         1         12500
3     O018        C014       P020  2025-01-18         2         22000
4     O019        C015       P019  2025-01-18         1         38000

  payment_mode order_status
0   Debit Card    Delivered
1  Credit Card      Pending
2         Cash    Delivered
3          UPI    Delivered
4  Net Banking      Shipped

In [6]:
#2 Append the datasets 

combined_df = pd.concat([df1, df2], axis=0, ignore_index=True)

combined_df.head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped

In [7]:
# 3. Create a new DataFrame named all_orders

all_orders = pd.concat([df1, df2])

all_orders

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped
5,O006,C004,P004,2025-01-11,2,3600,Credit Card,Delivered
6,O007,C005,P006,2025-01-11,1,22000,Net Banking,Pending
7,O008,C006,P009,2025-01-12,2,9000,UPI,Delivered
8,O009,C002,P007,2025-01-13,1,14500,Debit Card,Returned
9,O010,C007,P012,2025-01-13,3,4500,Cash,Delivered
10,O011,C008,P015,2025-01-14,5,3500,UPI,Delivered
11,O012,C009,P014,2025-01-15,1,5200,Credit Card,Cancelled
12,O013,C010,P011,2025-01-15,1,55000,Net Banking,Delivered
13,O014,C003,P013,2025-01-16,2,5600,UPI,Shipped
0,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered
1,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending
2,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered
3,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered
4,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped
5,O020,C001,P005,2025-01-19,4,3600,UPI,Delivered
6,O021,C002,P003,2025-01-19,1,2500,Cash,Delivered
7,O022,C003,P002,2025-01-20,1,28000,Credit Card,Delivered
8,O023,C004,P009,2025-01-20,2,9000,UPI,Pending
9,O024,C005,P008,2025-01-21,1,12000,Debit Card,Delivered
10,O025,C006,P010,2025-01-21,3,9600,Credit Card,Returned
11,O026,C007,P001,2025-01-22,1,65000,Net Banking,Delivered
12,O027,C008,P004,2025-01-22,2,3600,Cash,Delivered
13,O028,C009,P015,2025-01-23,10,7000,UPI,Delivered
14,O029,C010,P012,2025-01-23,4,6000,UPI,Cancelled
15,O030,C001,P014,2025-01-24,1,5200,Credit Card,Delivered

In [8]:
# 4. Find the total number of rows after concatenation

total_rows = len(all_orders)

total_rows

30

In [9]:
# 5. Display the first 10 rows of the combined dataset

all_orders.head(10)

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped
5,O006,C004,P004,2025-01-11,2,3600,Credit Card,Delivered
6,O007,C005,P006,2025-01-11,1,22000,Net Banking,Pending
7,O008,C006,P009,2025-01-12,2,9000,UPI,Delivered
8,O009,C002,P007,2025-01-13,1,14500,Debit Card,Returned
9,O010,C007,P012,2025-01-13,3,4500,Cash,Delivered

In [10]:
# 6. Display the last 10 rows of the combined dataset

all_orders.tail(10)

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
6,O021,C002,P003,2025-01-19,1,2500,Cash,Delivered
7,O022,C003,P002,2025-01-20,1,28000,Credit Card,Delivered
8,O023,C004,P009,2025-01-20,2,9000,UPI,Pending
9,O024,C005,P008,2025-01-21,1,12000,Debit Card,Delivered
10,O025,C006,P010,2025-01-21,3,9600,Credit Card,Returned
11,O026,C007,P001,2025-01-22,1,65000,Net Banking,Delivered
12,O027,C008,P004,2025-01-22,2,3600,Cash,Delivered
13,O028,C009,P015,2025-01-23,10,7000,UPI,Delivered
14,O029,C010,P012,2025-01-23,4,6000,UPI,Cancelled
15,O030,C001,P014,2025-01-24,1,5200,Credit Card,Delivered

In [11]:
# 7. Reset the index after concatenation

all_orders = all_orders.reset_index(drop=True)

all_orders

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped
5,O006,C004,P004,2025-01-11,2,3600,Credit Card,Delivered
6,O007,C005,P006,2025-01-11,1,22000,Net Banking,Pending
7,O008,C006,P009,2025-01-12,2,9000,UPI,Delivered
8,O009,C002,P007,2025-01-13,1,14500,Debit Card,Returned
9,O010,C007,P012,2025-01-13,3,4500,Cash,Delivered
10,O011,C008,P015,2025-01-14,5,3500,UPI,Delivered
11,O012,C009,P014,2025-01-15,1,5200,Credit Card,Cancelled
12,O013,C010,P011,2025-01-15,1,55000,Net Banking,Delivered
13,O014,C003,P013,2025-01-16,2,5600,UPI,Shipped
14,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered
15,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending
16,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered
17,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered
18,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped
19,O020,C001,P005,2025-01-19,4,3600,UPI,Delivered
20,O021,C002,P003,2025-01-19,1,2500,Cash,Delivered
21,O022,C003,P002,2025-01-20,1,28000,Credit Card,Delivered
22,O023,C004,P009,2025-01-20,2,9000,UPI,Pending
23,O024,C005,P008,2025-01-21,1,12000,Debit Card,Delivered
24,O025,C006,P010,2025-01-21,3,9600,Credit Card,Returned
25,O026,C007,P001,2025-01-22,1,65000,Net Banking,Delivered
26,O027,C008,P004,2025-01-22,2,3600,Cash,Delivered
27,O028,C009,P015,2025-01-23,10,7000,UPI,Delivered
28,O029,C010,P012,2025-01-23,4,6000,UPI,Cancelled
29,O030,C001,P014,2025-01-24,1,5200,Credit Card,Delivered

In [12]:
# 8. Check whether any duplicate order_id values exist

has_duplicates = all_orders["order_id"].duplicated().any()

has_duplicates

np.False_

In [13]:
# 9. Count the number of unique customers in the combined 

unique_customers = all_orders["customer_id"].nunique()

unique_customers

15

In [14]:
# 10. Count the number of unique products in the combined dataset

unique_products = all_orders["product_id"].nunique()

unique_products

20

In [15]:
# 11. Calculate the total sales amount from the combined dataset

total_sales = all_orders["total_amount"].sum()

total_sales

np.int64(501300)

In [16]:
# 12. Calculate the average order amount

avg_order = all_orders["total_amount"].mean()

avg_order

np.float64(16710.0)

In [17]:
# 13. Find the maximum order amount

max_order = all_orders["total_amount"].max()

max_order

np.int64(65000)

In [18]:
# 14. Find the minimum order amount

min_order = all_orders["total_amount"].min()

min_order

np.int64(2500)

In [19]:
# 15. Sort all orders by order_date

all_orders = all_orders.sort_values(by="order_date")

all_orders

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped
5,O006,C004,P004,2025-01-11,2,3600,Credit Card,Delivered
6,O007,C005,P006,2025-01-11,1,22000,Net Banking,Pending
7,O008,C006,P009,2025-01-12,2,9000,UPI,Delivered
8,O009,C002,P007,2025-01-13,1,14500,Debit Card,Returned
9,O010,C007,P012,2025-01-13,3,4500,Cash,Delivered
10,O011,C008,P015,2025-01-14,5,3500,UPI,Delivered
11,O012,C009,P014,2025-01-15,1,5200,Credit Card,Cancelled
12,O013,C010,P011,2025-01-15,1,55000,Net Banking,Delivered
14,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered
13,O014,C003,P013,2025-01-16,2,5600,UPI,Shipped
15,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending
16,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered
17,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered
18,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped
19,O020,C001,P005,2025-01-19,4,3600,UPI,Delivered
20,O021,C002,P003,2025-01-19,1,2500,Cash,Delivered
21,O022,C003,P002,2025-01-20,1,28000,Credit Card,Delivered
22,O023,C004,P009,2025-01-20,2,9000,UPI,Pending
23,O024,C005,P008,2025-01-21,1,12000,Debit Card,Delivered
24,O025,C006,P010,2025-01-21,3,9600,Credit Card,Returned
25,O026,C007,P001,2025-01-22,1,65000,Net Banking,Delivered
26,O027,C008,P004,2025-01-22,2,3600,Cash,Delivered
28,O029,C010,P012,2025-01-23,4,6000,UPI,Cancelled
27,O028,C009,P015,2025-01-23,10,7000,UPI,Delivered
29,O030,C001,P014,2025-01-24,1,5200,Credit Card,Delivered

In [20]:
# 16. Display all delivered orders

delivered_orders = all_orders[all_orders["order_status"] == "Delivered"]

delivered_orders.head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
5,O006,C004,P004,2025-01-11,2,3600,Credit Card,Delivered
7,O008,C006,P009,2025-01-12,2,9000,UPI,Delivered

In [21]:
# 17. Display all cancelled orders

cancelled_orders = all_orders[all_orders["order_status"] == "Cancelled"]

cancelled_orders

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
11,O012,C009,P014,2025-01-15,1,5200,Credit Card,Cancelled
28,O029,C010,P012,2025-01-23,4,6000,UPI,Cancelled

In [22]:
# 18. Find the total quantity sold

total_qty = all_orders["quantity"].sum()

total_qty

np.int64(62)

In [23]:
# 19. Group data by payment_mode and count 

payment_counts = all_orders.groupby("payment_mode").size()

payment_counts

payment_mode
Cash            5
Credit Card     7
Debit Card      4
Net Banking     4
UPI            10
dtype: int64

In [24]:
# 20. Export the combined dataset to all_orders.csv

all_orders.to_csv("all_orders.csv", index=False)

#### 🔵 Part 2: Merge Customers with Orders

In [25]:
import pandas as pd

df1 = pd.read_csv("../../dataset/orders.csv")
df2 = pd.read_csv("../../dataset/orders2.csv")

In [26]:
# 21. Load customers.csv and all_orders.csv

customers = pd.read_csv("../../dataset/customers.csv")
all_orders = pd.read_csv("../../dataset/all_orders.csv")

In [27]:
customers.head()

  customer_id customer_name gender       city        state signup_date
0        C001   Aarav Patel      M  Ahmedabad      Gujarat  2024-01-12
1        C002   Diya Sharma      F     Mumbai  Maharashtra  2024-02-18
2        C003  Vivaan Mehta      M      Surat      Gujarat  2024-03-05
3        C004  Ananya Verma      F      Delhi        Delhi  2024-01-28
4        C005    Krish Shah      M     Rajkot      Gujarat  2024-04-10

In [28]:
all_orders.head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped

In [29]:
# 22. Merge both datasets using customer_id

cust_orders = pd.merge(customers, all_orders, on="customer_id")

cust_orders.head()

,customer_id,customer_name,gender,city,state,signup_date,order_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O002,P003,2025-01-07,2,5000,UPI,Delivered
2,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O005,P010,2025-01-10,1,3200,UPI,Shipped
3,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O020,P005,2025-01-19,4,3600,UPI,Delivered
4,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O030,P014,2025-01-24,1,5200,Credit Card,Delivered

In [30]:
# 23. Display customer name and order amount

cust_orders[["customer_name", "total_amount"]].head()

  customer_name  total_amount
0   Aarav Patel         65000
1   Aarav Patel          5000
2   Aarav Patel          3200
3   Aarav Patel          3600
4   Aarav Patel          5200

In [31]:
# 24. Display customer name, city, and order status

cust_orders[["customer_name", "city", "order_status"]].head()

  customer_name       city order_status
0   Aarav Patel  Ahmedabad    Delivered
1   Aarav Patel  Ahmedabad    Delivered
2   Aarav Patel  Ahmedabad      Shipped
3   Aarav Patel  Ahmedabad    Delivered
4   Aarav Patel  Ahmedabad    Delivered

In [32]:
# 25. Find the total amount spent by each customer

cust_spending = (cust_orders.groupby("customer_name")["total_amount"].sum().reset_index())

cust_spending

   customer_name  total_amount
0    Aarav Patel         82000
1     Aditya Rao         38000
2   Ananya Verma         12600
3    Arjun Singh         12200
4   Dev Malhotra         12500
5    Diya Sharma         45000
6     Isha Joshi         18600
7     Kavya Nair          7100
8     Krish Shah         34000
9   Meera Kapoor         61000
10   Riya Pandey         22000
11   Rohan Desai         69500
12   Simran Kaur         42000
13  Vivaan Mehta         36300
14  Yash Trivedi          8500

In [33]:
# 26. Find the customer with the highest spending

highest_spender = cust_spending.loc[cust_spending["total_amount"].idxmax()]

highest_spender

customer_name    Aarav Patel
total_amount           82000
Name: 0, dtype: object

In [34]:
# 27. Count orders placed by each customer

order_counts = cust_orders.groupby("customer_name").size().reset_index(name="order_count")

order_counts

   customer_name  order_count
0    Aarav Patel            5
1     Aditya Rao            1
2   Ananya Verma            2
3    Arjun Singh            2
4   Dev Malhotra            1
5    Diya Sharma            3
6     Isha Joshi            2
7     Kavya Nair            2
8     Krish Shah            2
9   Meera Kapoor            2
10   Riya Pandey            1
11   Rohan Desai            2
12   Simran Kaur            1
13  Vivaan Mehta            3
14  Yash Trivedi            1

In [1]:
# 28. Find customers who placed more than one order

multi_order_cust = order_counts[order_counts["order_count"] > 1]

multi_order_cust

NameError: name 'order_counts' is not defined

In [36]:
# 29. Display all female customers and their orders

female_orders = cust_orders[cust_orders["gender"] == "Female"]

female_orders

Empty DataFrame
Columns: [customer_id, customer_name, gender, city, state, signup_date, order_id, product_id, order_date, quantity, total_amount, payment_mode, order_status]
Index: []

In [37]:
# 30. Display all male customers and their orders

male_orders = cust_orders[cust_orders["gender"] == "Male"]

male_orders

Empty DataFrame
Columns: [customer_id, customer_name, gender, city, state, signup_date, order_id, product_id, order_date, quantity, total_amount, payment_mode, order_status]
Index: []

In [38]:
# 31. Find total sales generated from each city

city_sales = cust_orders.groupby("city")["total_amount"].sum().reset_index()

city_sales

          city  total_amount
0    Ahmedabad         90500
1    Bengaluru          7100
2   Chandigarh         61000
3        Delhi         25100
4    Hyderabad         38000
5       Jaipur         12200
6     Ludhiana         42000
7       Mumbai         45000
8        Patna         22000
9         Pune         18600
10      Rajkot         34000
11       Surat         36300
12    Vadodara         69500

In [39]:
# 32. Find total sales generated from each state

state_sales = cust_orders.groupby("state")["total_amount"].sum().reset_index()

state_sales

         state  total_amount
0        Bihar         22000
1   Chandigarh         61000
2        Delhi         25100
3      Gujarat        230300
4    Karnataka          7100
5  Maharashtra         63600
6       Punjab         42000
7    Rajasthan         12200
8    Telangana         38000

In [40]:
# 33. Display customer details for cancelled orders

cancelled_cust_details = cust_orders[cust_orders["order_status"] == "Cancelled"][customers.columns].drop_duplicates()

cancelled_cust_details

   customer_id customer_name gender        city        state signup_date
5         C002   Diya Sharma      F      Mumbai  Maharashtra  2024-02-18
21        C009   Arjun Singh      M      Jaipur    Rajasthan  2024-05-01
24        C010  Meera Kapoor      F  Chandigarh   Chandigarh  2024-02-26

In [41]:
# 34. Display customer details for delivered orders

delivered_cust_details = cust_orders[cust_orders["order_status"] == "Delivered"][customers.columns].drop_duplicates()

delivered_cust_details

   customer_id customer_name gender        city        state signup_date
0         C001   Aarav Patel      M   Ahmedabad      Gujarat  2024-01-12
7         C002   Diya Sharma      F      Mumbai  Maharashtra  2024-02-18
8         C003  Vivaan Mehta      M       Surat      Gujarat  2024-03-05
11        C004  Ananya Verma      F       Delhi        Delhi  2024-01-28
14        C005    Krish Shah      M      Rajkot      Gujarat  2024-04-10
15        C006    Isha Joshi      F        Pune  Maharashtra  2024-02-02
17        C007   Rohan Desai      M    Vadodara      Gujarat  2024-03-19
19        C008    Kavya Nair      F   Bengaluru    Karnataka  2024-01-14
22        C009   Arjun Singh      M      Jaipur    Rajasthan  2024-05-01
23        C010  Meera Kapoor      F  Chandigarh   Chandigarh  2024-02-26
25        C011  Yash Trivedi      M   Ahmedabad      Gujarat  2024-03-30
27        C013  Dev Malhotra      M       Delhi        Delhi  2024-01-20
28        C014   Riya Pandey      F       Patna        Bihar  2024-05-05

In [42]:
# 35. Find the average order amount by gender

avg_by_gender = cust_orders.groupby("gender")["total_amount"].mean().reset_index()

avg_by_gender

  gender  total_amount
0      F  16023.076923
1      M  17235.294118

In [43]:
# 36. Find customers who paid using UPI

upi_customers = cust_orders[cust_orders["payment_mode"] == "UPI"]["customer_name"].unique()

upi_customers

<StringArray>
[ 'Aarav Patel', 'Vivaan Mehta', 'Ananya Verma',   'Isha Joshi',
   'Kavya Nair',  'Arjun Singh', 'Meera Kapoor',  'Riya Pandey']
Length: 8, dtype: str

In [44]:
# 37. Find customers who paid using Credit Card

cc_customers = cust_orders[cust_orders["payment_mode"] == "Credit Card"]["customer_name"].unique()

cc_customers

<StringArray>
[ 'Aarav Patel', 'Vivaan Mehta', 'Ananya Verma',   'Isha Joshi',
  'Arjun Singh',  'Simran Kaur']
Length: 6, dtype: str

In [45]:
# 38. Find customers with pending orders

pending_customers = cust_orders[cust_orders["order_status"] == "Pending"]["customer_name"].unique()

pending_customers

<StringArray>
['Ananya Verma', 'Krish Shah', 'Simran Kaur']
Length: 3, dtype: str

In [46]:
# 39. Sort merged data by customer name

cust_orders_sorted = cust_orders.sort_values(by="customer_name")

cust_orders_sorted

,customer_id,customer_name,gender,city,state,signup_date,order_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O002,P003,2025-01-07,2,5000,UPI,Delivered
2,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O005,P010,2025-01-10,1,3200,UPI,Shipped
3,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O020,P005,2025-01-19,4,3600,UPI,Delivered
4,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O030,P014,2025-01-24,1,5200,Credit Card,Delivered
29,C015,Aditya Rao,M,Hyderabad,Telangana,2024-03-12,O019,P019,2025-01-18,1,38000,Net Banking,Shipped
11,C004,Ananya Verma,F,Delhi,Delhi,2024-01-28,O006,P004,2025-01-11,2,3600,Credit Card,Delivered
12,C004,Ananya Verma,F,Delhi,Delhi,2024-01-28,O023,P009,2025-01-20,2,9000,UPI,Pending
22,C009,Arjun Singh,M,Jaipur,Rajasthan,2024-05-01,O028,P015,2025-01-23,10,7000,UPI,Delivered
21,C009,Arjun Singh,M,Jaipur,Rajasthan,2024-05-01,O012,P014,2025-01-15,1,5200,Credit Card,Cancelled
27,C013,Dev Malhotra,M,Delhi,Delhi,2024-01-20,O017,P017,2025-01-17,1,12500,Cash,Delivered
6,C002,Diya Sharma,F,Mumbai,Maharashtra,2024-02-18,O009,P007,2025-01-13,1,14500,Debit Card,Returned
7,C002,Diya Sharma,F,Mumbai,Maharashtra,2024-02-18,O021,P003,2025-01-19,1,2500,Cash,Delivered
5,C002,Diya Sharma,F,Mumbai,Maharashtra,2024-02-18,O003,P002,2025-01-08,1,28000,Debit Card,Cancelled
15,C006,Isha Joshi,F,Pune,Maharashtra,2024-02-02,O008,P009,2025-01-12,2,9000,UPI,Delivered
16,C006,Isha Joshi,F,Pune,Maharashtra,2024-02-02,O025,P010,2025-01-21,3,9600,Credit Card,Returned
20,C008,Kavya Nair,F,Bengaluru,Karnataka,2024-01-14,O027,P004,2025-01-22,2,3600,Cash,Delivered
19,C008,Kavya Nair,F,Bengaluru,Karnataka,2024-01-14,O011,P015,2025-01-14,5,3500,UPI,Delivered
14,C005,Krish Shah,M,Rajkot,Gujarat,2024-04-10,O024,P008,2025-01-21,1,12000,Debit Card,Delivered
13,C005,Krish Shah,M,Rajkot,Gujarat,2024-04-10,O007,P006,2025-01-11,1,22000,Net Banking,Pending
23,C010,Meera Kapoor,F,Chandigarh,Chandigarh,2024-02-26,O013,P011,2025-01-15,1,55000,Net Banking,Delivered
24,C010,Meera Kapoor,F,Chandigarh,Chandigarh,2024-02-26,O029,P012,2025-01-23,4,6000,UPI,Cancelled
28,C014,Riya Pandey,F,Patna,Bihar,2024-05-05,O018,P020,2025-01-18,2,22000,UPI,Delivered
18,C007,Rohan Desai,M,Vadodara,Gujarat,2024-03-19,O026,P001,2025-01-22,1,65000,Net Banking,Delivered
17,C007,Rohan Desai,M,Vadodara,Gujarat,2024-03-19,O010,P012,2025-01-13,3,4500,Cash,Delivered
26,C012,Simran Kaur,F,Ludhiana,Punjab,2024-04-15,O016,P018,2025-01-17,1,42000,Credit Card,Pending
10,C003,Vivaan Mehta,M,Surat,Gujarat,2024-03-05,O022,P002,2025-01-20,1,28000,Credit Card,Delivered
9,C003,Vivaan Mehta,M,Surat,Gujarat,2024-03-05,O014,P013,2025-01-16,2,5600,UPI,Shipped
8,C003,Vivaan Mehta,M,Surat,Gujarat,2024-03-05,O004,P005,2025-01-08,3,2700,Cash,Delivered
25,C011,Yash Trivedi,M,Ahmedabad,Gujarat,2024-03-30,O015,P016,2025-01-16,1,8500,Debit Card,Delivered

In [47]:
# 40. Display the top 5 customers based on total spending

top_5_spend = cust_spending.sort_values(by="total_amount", ascending=False).head(5)

top_5_spend

   customer_name  total_amount
0    Aarav Patel         82000
11   Rohan Desai         69500
9   Meera Kapoor         61000
5    Diya Sharma         45000
12   Simran Kaur         42000

#### 🟣 Part 3: Merge Products with Orders

In [48]:
import pandas as pd

In [49]:
# 41. Load products.csv and all_orders.csv

products = pd.read_csv("../../dataset/products.csv")

products.head()

  product_id product_name     category     brand  price  stock  rating
0       P001       Laptop  Electronics        HP  65000     15     4.5
1       P002   Smartphone  Electronics   Samsung  28000     30     4.3
2       P003   Headphones  Accessories      Boat   2500     50     4.1
3       P004     Keyboard  Accessories  Logitech   1800     40     4.4
4       P005        Mouse  Accessories        HP    900     60     4.0

In [50]:
# 42. Merge both datasets using product_id

prod_orders = pd.merge(products, all_orders, on="product_id")

prod_orders

,product_id,product_name,category,brand,price,stock,rating,order_id,customer_id,order_date,quantity,total_amount,payment_mode,order_status
0,P001,Laptop,Electronics,HP,65000,15,4.5,O001,C001,2025-01-05,1,65000,Credit Card,Delivered
1,P001,Laptop,Electronics,HP,65000,15,4.5,O026,C007,2025-01-22,1,65000,Net Banking,Delivered
2,P002,Smartphone,Electronics,Samsung,28000,30,4.3,O003,C002,2025-01-08,1,28000,Debit Card,Cancelled
3,P002,Smartphone,Electronics,Samsung,28000,30,4.3,O022,C003,2025-01-20,1,28000,Credit Card,Delivered
4,P003,Headphones,Accessories,Boat,2500,50,4.1,O002,C001,2025-01-07,2,5000,UPI,Delivered
5,P003,Headphones,Accessories,Boat,2500,50,4.1,O021,C002,2025-01-19,1,2500,Cash,Delivered
6,P004,Keyboard,Accessories,Logitech,1800,40,4.4,O006,C004,2025-01-11,2,3600,Credit Card,Delivered
7,P004,Keyboard,Accessories,Logitech,1800,40,4.4,O027,C008,2025-01-22,2,3600,Cash,Delivered
8,P005,Mouse,Accessories,HP,900,60,4.0,O004,C003,2025-01-08,3,2700,Cash,Delivered
9,P005,Mouse,Accessories,HP,900,60,4.0,O020,C001,2025-01-19,4,3600,UPI,Delivered
10,P006,Tablet,Electronics,Lenovo,22000,20,4.2,O007,C005,2025-01-11,1,22000,Net Banking,Pending
11,P007,Monitor,Electronics,Dell,14500,18,4.6,O009,C002,2025-01-13,1,14500,Debit Card,Returned
12,P008,Printer,Electronics,Canon,12000,10,4.1,O024,C005,2025-01-21,1,12000,Debit Card,Delivered
13,P009,Smartwatch,Wearables,Noise,4500,35,4.0,O008,C006,2025-01-12,2,9000,UPI,Delivered
14,P009,Smartwatch,Wearables,Noise,4500,35,4.0,O023,C004,2025-01-20,2,9000,UPI,Pending
15,P010,Speaker,Accessories,JBL,3200,25,4.5,O005,C001,2025-01-10,1,3200,UPI,Shipped
16,P010,Speaker,Accessories,JBL,3200,25,4.5,O025,C006,2025-01-21,3,9600,Credit Card,Returned
17,P011,Camera,Electronics,Sony,55000,8,4.7,O013,C010,2025-01-15,1,55000,Net Banking,Delivered
18,P012,Power Bank,Accessories,Mi,1500,45,3.9,O010,C007,2025-01-13,3,4500,Cash,Delivered
19,P012,Power Bank,Accessories,Mi,1500,45,3.9,O029,C010,2025-01-23,4,6000,UPI,Cancelled
20,P013,Router,Networking,TP-Link,2800,22,4.2,O014,C003,2025-01-16,2,5600,UPI,Shipped
21,P014,External HDD,Storage,Seagate,5200,16,4.4,O012,C009,2025-01-15,1,5200,Credit Card,Cancelled
22,P014,External HDD,Storage,Seagate,5200,16,4.4,O030,C001,2025-01-24,1,5200,Credit Card,Delivered
23,P015,Pen Drive,Storage,SanDisk,700,80,4.0,O011,C008,2025-01-14,5,3500,UPI,Delivered
24,P015,Pen Drive,Storage,SanDisk,700,80,4.0,O028,C009,2025-01-23,10,7000,UPI,Delivered
25,P016,Office Chair,Furniture,GreenSoul,8500,12,4.3,O015,C011,2025-01-16,1,8500,Debit Card,Delivered
26,P017,Study Table,Furniture,Ikea,12500,9,4.5,O017,C013,2025-01-17,1,12500,Cash,Delivered
27,P018,Air Conditioner,Home Appliances,LG,42000,7,4.6,O016,C012,2025-01-17,1,42000,Credit Card,Pending
28,P019,Refrigerator,Home Appliances,Samsung,38000,6,4.4,O019,C015,2025-01-18,1,38000,Net Banking,Shipped
29,P020,Microwave,Home Appliances,IFB,11000,11,4.1,O018,C014,2025-01-18,2,22000,UPI,Delivered

In [51]:
# 43. Display product name and quantity sold

prod_orders[["product_name", "quantity"]]

       product_name  quantity
0            Laptop         1
1            Laptop         1
2        Smartphone         1
3        Smartphone         1
4        Headphones         2
5        Headphones         1
6          Keyboard         2
7          Keyboard         2
8             Mouse         3
9             Mouse         4
10           Tablet         1
11          Monitor         1
12          Printer         1
13       Smartwatch         2
14       Smartwatch         2
15          Speaker         1
16          Speaker         3
17           Camera         1
18       Power Bank         3
19       Power Bank         4
20           Router         2
21     External HDD         1
22     External HDD         1
23        Pen Drive         5
24        Pen Drive        10
25     Office Chair         1
26      Study Table         1
27  Air Conditioner         1
28     Refrigerator         1
29        Microwave         2

In [52]:
# 44. Find total revenue generated by each product

prod_revenue = (prod_orders.groupby("product_name")["total_amount"].sum().reset_index())

prod_revenue

       product_name  total_amount
0   Air Conditioner         42000
1            Camera         55000
2      External HDD         10400
3        Headphones          7500
4          Keyboard          7200
5            Laptop        130000
6         Microwave         22000
7           Monitor         14500
8             Mouse          6300
9      Office Chair          8500
10        Pen Drive         10500
11       Power Bank         10500
12          Printer         12000
13     Refrigerator         38000
14           Router          5600
15       Smartphone         56000
16       Smartwatch         18000
17          Speaker         12800
18      Study Table         12500
19           Tablet         22000

In [53]:
# 45. Find the most sold product by quantity

prod_qty = prod_orders.groupby("product_name")["quantity"].sum().reset_index()

most_sold_qty = prod_qty.loc[prod_qty["quantity"].idxmax()]

most_sold_qty

product_name    Pen Drive
quantity               15
Name: 10, dtype: object

In [54]:
prod_qty.sort_values(by="quantity", ascending=False).reset_index().loc[0]

index                  10
product_name    Pen Drive
quantity               15
Name: 0, dtype: object

In [55]:
most_sold_qty.head()

product_name    Pen Drive
quantity               15
Name: 10, dtype: object

In [56]:
# 46. Find the least sold product by quantity

least_sold_qty = prod_qty.loc[prod_qty["quantity"].idxmin()]

least_sold_qty

product_name    Air Conditioner
quantity                      1
Name: 0, dtype: object

In [57]:
# 47. Display all Electronics product orders

electronics_orders = prod_orders[prod_orders["category"] == "Electronics"]

electronics_orders

,product_id,product_name,category,brand,price,stock,rating,order_id,customer_id,order_date,quantity,total_amount,payment_mode,order_status
0,P001,Laptop,Electronics,HP,65000,15,4.5,O001,C001,2025-01-05,1,65000,Credit Card,Delivered
1,P001,Laptop,Electronics,HP,65000,15,4.5,O026,C007,2025-01-22,1,65000,Net Banking,Delivered
2,P002,Smartphone,Electronics,Samsung,28000,30,4.3,O003,C002,2025-01-08,1,28000,Debit Card,Cancelled
3,P002,Smartphone,Electronics,Samsung,28000,30,4.3,O022,C003,2025-01-20,1,28000,Credit Card,Delivered
10,P006,Tablet,Electronics,Lenovo,22000,20,4.2,O007,C005,2025-01-11,1,22000,Net Banking,Pending
11,P007,Monitor,Electronics,Dell,14500,18,4.6,O009,C002,2025-01-13,1,14500,Debit Card,Returned
12,P008,Printer,Electronics,Canon,12000,10,4.1,O024,C005,2025-01-21,1,12000,Debit Card,Delivered
17,P011,Camera,Electronics,Sony,55000,8,4.7,O013,C010,2025-01-15,1,55000,Net Banking,Delivered

In [58]:
# 48. Display all Accessories product orders

accessories_orders = prod_orders[prod_orders["category"] == "Accessories"]

accessories_orders

,product_id,product_name,category,brand,price,stock,rating,order_id,customer_id,order_date,quantity,total_amount,payment_mode,order_status
4,P003,Headphones,Accessories,Boat,2500,50,4.1,O002,C001,2025-01-07,2,5000,UPI,Delivered
5,P003,Headphones,Accessories,Boat,2500,50,4.1,O021,C002,2025-01-19,1,2500,Cash,Delivered
6,P004,Keyboard,Accessories,Logitech,1800,40,4.4,O006,C004,2025-01-11,2,3600,Credit Card,Delivered
7,P004,Keyboard,Accessories,Logitech,1800,40,4.4,O027,C008,2025-01-22,2,3600,Cash,Delivered
8,P005,Mouse,Accessories,HP,900,60,4.0,O004,C003,2025-01-08,3,2700,Cash,Delivered
9,P005,Mouse,Accessories,HP,900,60,4.0,O020,C001,2025-01-19,4,3600,UPI,Delivered
15,P010,Speaker,Accessories,JBL,3200,25,4.5,O005,C001,2025-01-10,1,3200,UPI,Shipped
16,P010,Speaker,Accessories,JBL,3200,25,4.5,O025,C006,2025-01-21,3,9600,Credit Card,Returned
18,P012,Power Bank,Accessories,Mi,1500,45,3.9,O010,C007,2025-01-13,3,4500,Cash,Delivered
19,P012,Power Bank,Accessories,Mi,1500,45,3.9,O029,C010,2025-01-23,4,6000,UPI,Cancelled

In [59]:
# 49. Find total sales by category

cat_sales = prod_orders.groupby("category")["total_amount"].sum().reset_index()

cat_sales

          category  total_amount
0      Accessories         44300
1      Electronics        289500
2        Furniture         21000
3  Home Appliances        102000
4       Networking          5600
5          Storage         20900
6        Wearables         18000

In [60]:
# 50. Find total sales by brand

brand_sales = prod_orders.groupby("brand")["total_amount"].sum().reset_index()

brand_sales

        brand  total_amount
0        Boat          7500
1       Canon         12000
2        Dell         14500
3   GreenSoul          8500
4          HP        136300
5         IFB         22000
6        Ikea         12500
7         JBL         12800
8          LG         42000
9      Lenovo         22000
10   Logitech          7200
11         Mi         10500
12      Noise         18000
13    Samsung         94000
14    SanDisk         10500
15    Seagate         10400
16       Sony         55000
17    TP-Link          5600

In [61]:
# 51. Display products with rating greater than 4.5

high_rated = products[products["rating"] > 4.5]

high_rated

   product_id     product_name         category brand  price  stock  rating
6        P007          Monitor      Electronics  Dell  14500     18     4.6
10       P011           Camera      Electronics  Sony  55000      8     4.7
17       P018  Air Conditioner  Home Appliances    LG  42000      7     4.6

In [62]:
# 52. Display product name, brand, quantity, and total amount

prod_orders[["product_name", "brand", "quantity", "total_amount"]].head()

  product_name    brand  quantity  total_amount
0       Laptop       HP         1         65000
1       Laptop       HP         1         65000
2   Smartphone  Samsung         1         28000
3   Smartphone  Samsung         1         28000
4   Headphones     Boat         2          5000

In [63]:
# 53. Find average quantity sold per product

avg_qty_sold = prod_orders.groupby("product_name")["quantity"].mean().reset_index()

avg_qty_sold

       product_name  quantity
0   Air Conditioner       1.0
1            Camera       1.0
2      External HDD       1.0
3        Headphones       1.5
4          Keyboard       2.0
5            Laptop       1.0
6         Microwave       2.0
7           Monitor       1.0
8             Mouse       3.5
9      Office Chair       1.0
10        Pen Drive       7.5
11       Power Bank       3.5
12          Printer       1.0
13     Refrigerator       1.0
14           Router       2.0
15       Smartphone       1.0
16       Smartwatch       2.0
17          Speaker       2.0
18      Study Table       1.0
19           Tablet       1.0

In [64]:
# 54. Display the top 5 products by revenue

top_5_rev_products = prod_revenue.sort_values(by="total_amount", ascending=False).head(5)

top_5_rev_products

       product_name  total_amount
5            Laptop        130000
15       Smartphone         56000
1            Camera         55000
0   Air Conditioner         42000
13     Refrigerator         38000

In [65]:
# 55. Find products that were never ordered

never_ordered = products[~products["product_id"].isin(all_orders["product_id"])]

never_ordered

Empty DataFrame
Columns: [product_id, product_name, category, brand, price, stock, rating]
Index: []

In [66]:
# 56. Display orders where quantity is greater than 2

high_qty_orders = all_orders[all_orders["quantity"] > 2]

high_qty_orders

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
9,O010,C007,P012,2025-01-13,3,4500,Cash,Delivered
10,O011,C008,P015,2025-01-14,5,3500,UPI,Delivered
19,O020,C001,P005,2025-01-19,4,3600,UPI,Delivered
24,O025,C006,P010,2025-01-21,3,9600,Credit Card,Returned
27,O028,C009,P015,2025-01-23,10,7000,UPI,Delivered
28,O029,C010,P012,2025-01-23,4,6000,UPI,Cancelled

In [67]:
# 57. Find products sold through UPI payments

upi_products = prod_orders[prod_orders["payment_mode"] == "UPI"]["product_name"].unique()

upi_products

<StringArray>
['Headphones',      'Mouse', 'Smartwatch',    'Speaker', 'Power Bank',
     'Router',  'Pen Drive',  'Microwave']
Length: 8, dtype: str

In [68]:
# 58. Find total quantity sold by brand

brand_qty = prod_orders.groupby("brand")["quantity"].sum().reset_index()

brand_qty

        brand  quantity
0        Boat         3
1       Canon         1
2        Dell         1
3   GreenSoul         1
4          HP         9
5         IFB         2
6        Ikea         1
7         JBL         4
8          LG         1
9      Lenovo         1
10   Logitech         4
11         Mi         7
12      Noise         4
13    Samsung         3
14    SanDisk        15
15    Seagate         2
16       Sony         1
17    TP-Link         2

In [69]:
# 59. Find the category with the highest revenue

highest_rev_cat = cat_sales.loc[cat_sales["total_amount"].idxmax()]

highest_rev_cat

category        Electronics
total_amount         289500
Name: 1, dtype: object

In [70]:
# 60. Display product details for cancelled orders

cancelled_prod_details = prod_orders[prod_orders["order_status"] == "Cancelled"][products.columns]

cancelled_prod_details

   product_id  product_name     category    brand  price  stock  rating
2        P002    Smartphone  Electronics  Samsung  28000     30     4.3
19       P012    Power Bank  Accessories       Mi   1500     45     3.9
21       P014  External HDD      Storage  Seagate   5200     16     4.4

#### 🔴 Part 4: Merge Customers + Products + Orders

In [71]:
import pandas as pd

In [72]:
pd.read_csv("../../dataset/products.csv").head()

  product_id product_name     category     brand  price  stock  rating
0       P001       Laptop  Electronics        HP  65000     15     4.5
1       P002   Smartphone  Electronics   Samsung  28000     30     4.3
2       P003   Headphones  Accessories      Boat   2500     50     4.1
3       P004     Keyboard  Accessories  Logitech   1800     40     4.4
4       P005        Mouse  Accessories        HP    900     60     4.0

In [73]:
pd.read_csv("../../dataset/orders.csv").head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped

In [74]:
pd.read_csv("../../dataset/orders2.csv").head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered
1,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending
2,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered
3,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered
4,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped

In [75]:
pd.read_csv("../../dataset/customers.csv").head()

  customer_id customer_name gender       city        state signup_date
0        C001   Aarav Patel      M  Ahmedabad      Gujarat  2024-01-12
1        C002   Diya Sharma      F     Mumbai  Maharashtra  2024-02-18
2        C003  Vivaan Mehta      M      Surat      Gujarat  2024-03-05
3        C004  Ananya Verma      F      Delhi        Delhi  2024-01-28
4        C005    Krish Shah      M     Rajkot      Gujarat  2024-04-10

In [76]:
pd.read_csv("../../dataset/payments.csv").head()

     name gender  amount month       city payment_method     category
0   Aarav      M  1200.0   Jan  Ahmedabad            UPI         Food
1  Vivaan      M  1500.0   Jan     Mumbai           Card     Shopping
2  Aditya      M     NaN   Jan      Delhi           Cash        Bills
3  Vihaan      M  1100.0   Jan       Pune            UPI    Transport
4   Arjun      M  2000.0   Jan  Bangalore           Card  Electronics

In [77]:
pd.read_csv("../../dataset/all_orders.csv").head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped

In [78]:
# 61. Merge all three datasets together

final_df = pd.merge(cust_orders, products, on="product_id")

final_df

,customer_id,customer_name,gender,city,state,signup_date,order_id,product_id,order_date,quantity,total_amount,payment_mode,order_status,product_name,category,brand,price,stock,rating
0,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O001,P001,2025-01-05,1,65000,Credit Card,Delivered,Laptop,Electronics,HP,65000,15,4.5
1,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O002,P003,2025-01-07,2,5000,UPI,Delivered,Headphones,Accessories,Boat,2500,50,4.1
2,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O005,P010,2025-01-10,1,3200,UPI,Shipped,Speaker,Accessories,JBL,3200,25,4.5
3,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O020,P005,2025-01-19,4,3600,UPI,Delivered,Mouse,Accessories,HP,900,60,4.0
4,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O030,P014,2025-01-24,1,5200,Credit Card,Delivered,External HDD,Storage,Seagate,5200,16,4.4
5,C002,Diya Sharma,F,Mumbai,Maharashtra,2024-02-18,O003,P002,2025-01-08,1,28000,Debit Card,Cancelled,Smartphone,Electronics,Samsung,28000,30,4.3
6,C002,Diya Sharma,F,Mumbai,Maharashtra,2024-02-18,O009,P007,2025-01-13,1,14500,Debit Card,Returned,Monitor,Electronics,Dell,14500,18,4.6
7,C002,Diya Sharma,F,Mumbai,Maharashtra,2024-02-18,O021,P003,2025-01-19,1,2500,Cash,Delivered,Headphones,Accessories,Boat,2500,50,4.1
8,C003,Vivaan Mehta,M,Surat,Gujarat,2024-03-05,O004,P005,2025-01-08,3,2700,Cash,Delivered,Mouse,Accessories,HP,900,60,4.0
9,C003,Vivaan Mehta,M,Surat,Gujarat,2024-03-05,O014,P013,2025-01-16,2,5600,UPI,Shipped,Router,Networking,TP-Link,2800,22,4.2
10,C003,Vivaan Mehta,M,Surat,Gujarat,2024-03-05,O022,P002,2025-01-20,1,28000,Credit Card,Delivered,Smartphone,Electronics,Samsung,28000,30,4.3
11,C004,Ananya Verma,F,Delhi,Delhi,2024-01-28,O006,P004,2025-01-11,2,3600,Credit Card,Delivered,Keyboard,Accessories,Logitech,1800,40,4.4
12,C004,Ananya Verma,F,Delhi,Delhi,2024-01-28,O023,P009,2025-01-20,2,9000,UPI,Pending,Smartwatch,Wearables,Noise,4500,35,4.0
13,C005,Krish Shah,M,Rajkot,Gujarat,2024-04-10,O007,P006,2025-01-11,1,22000,Net Banking,Pending,Tablet,Electronics,Lenovo,22000,20,4.2
14,C005,Krish Shah,M,Rajkot,Gujarat,2024-04-10,O024,P008,2025-01-21,1,12000,Debit Card,Delivered,Printer,Electronics,Canon,12000,10,4.1
15,C006,Isha Joshi,F,Pune,Maharashtra,2024-02-02,O008,P009,2025-01-12,2,9000,UPI,Delivered,Smartwatch,Wearables,Noise,4500,35,4.0
16,C006,Isha Joshi,F,Pune,Maharashtra,2024-02-02,O025,P010,2025-01-21,3,9600,Credit Card,Returned,Speaker,Accessories,JBL,3200,25,4.5
17,C007,Rohan Desai,M,Vadodara,Gujarat,2024-03-19,O010,P012,2025-01-13,3,4500,Cash,Delivered,Power Bank,Accessories,Mi,1500,45,3.9
18,C007,Rohan Desai,M,Vadodara,Gujarat,2024-03-19,O026,P001,2025-01-22,1,65000,Net Banking,Delivered,Laptop,Electronics,HP,65000,15,4.5
19,C008,Kavya Nair,F,Bengaluru,Karnataka,2024-01-14,O011,P015,2025-01-14,5,3500,UPI,Delivered,Pen Drive,Storage,SanDisk,700,80,4.0
20,C008,Kavya Nair,F,Bengaluru,Karnataka,2024-01-14,O027,P004,2025-01-22,2,3600,Cash,Delivered,Keyboard,Accessories,Logitech,1800,40,4.4
21,C009,Arjun Singh,M,Jaipur,Rajasthan,2024-05-01,O012,P014,2025-01-15,1,5200,Credit Card,Cancelled,External HDD,Storage,Seagate,5200,16,4.4
22,C009,Arjun Singh,M,Jaipur,Rajasthan,2024-05-01,O028,P015,2025-01-23,10,7000,UPI,Delivered,Pen Drive,Storage,SanDisk,700,80,4.0
23,C010,Meera Kapoor,F,Chandigarh,Chandigarh,2024-02-26,O013,P011,2025-01-15,1,55000,Net Banking,Delivered,Camera,Electronics,Sony,55000,8,4.7
24,C010,Meera Kapoor,F,Chandigarh,Chandigarh,2024-02-26,O029,P012,2025-01-23,4,6000,UPI,Cancelled,Power Bank,Accessories,Mi,1500,45,3.9
25,C011,Yash Trivedi,M,Ahmedabad,Gujarat,2024-03-30,O015,P016,2025-01-16,1,8500,Debit Card,Delivered,Office Chair,Furniture,GreenSoul,8500,12,4.3
26,C012,Simran Kaur,F,Ludhiana,Punjab,2024-04-15,O016,P018,2025-01-17,1,42000,Credit Card,Pending,Air Conditioner,Home Appliances,LG,42000,7,4.6
27,C013,Dev Malhotra,M,Delhi,Delhi,2024-01-20,O017,P017,2025-01-17,1,12500,Cash,Delivered,Study Table,Furniture,Ikea,12500,9,4.5
28,C014,Riya Pandey,F,Patna,Bihar,2024-05-05,O018,P020,2025-01-18,2,22000,UPI,Delivered,Microwave,Home Appliances,IFB,11000,11,4.1
29,C015,Aditya Rao,M,Hyderabad,Telangana,2024-03-12,O019,P019,2025-01-18,1,38000,Net Banking,Shipped,Refrigerator,Home Appliances,Samsung,38000,6,4.4

In [79]:
# 62. Display customer name, product name, quantity, and total amount

final_df[["customer_name", "product_name", "quantity", "total_amount"]]

   customer_name     product_name  quantity  total_amount
0    Aarav Patel           Laptop         1         65000
1    Aarav Patel       Headphones         2          5000
2    Aarav Patel          Speaker         1          3200
3    Aarav Patel            Mouse         4          3600
4    Aarav Patel     External HDD         1          5200
5    Diya Sharma       Smartphone         1         28000
6    Diya Sharma          Monitor         1         14500
7    Diya Sharma       Headphones         1          2500
8   Vivaan Mehta            Mouse         3          2700
9   Vivaan Mehta           Router         2          5600
10  Vivaan Mehta       Smartphone         1         28000
11  Ananya Verma         Keyboard         2          3600
12  Ananya Verma       Smartwatch         2          9000
13    Krish Shah           Tablet         1         22000
14    Krish Shah          Printer         1         12000
15    Isha Joshi       Smartwatch         2          9000
16    Isha Joshi          Speaker         3          9600
17   Rohan Desai       Power Bank         3          4500
18   Rohan Desai           Laptop         1         65000
19    Kavya Nair        Pen Drive         5          3500
20    Kavya Nair         Keyboard         2          3600
21   Arjun Singh     External HDD         1          5200
22   Arjun Singh        Pen Drive        10          7000
23  Meera Kapoor           Camera         1         55000
24  Meera Kapoor       Power Bank         4          6000
25  Yash Trivedi     Office Chair         1          8500
26   Simran Kaur  Air Conditioner         1         42000
27  Dev Malhotra      Study Table         1         12500
28   Riya Pandey        Microwave         2         22000
29    Aditya Rao     Refrigerator         1         38000

In [80]:
# 63. Find total spending of each customer on each product

cust_prod_spend = (final_df.groupby(["product_id", "product_name"])["price"].sum().reset_index())

cust_prod_spend

   product_id     product_name   price
0        P001           Laptop  130000
1        P002       Smartphone   56000
2        P003       Headphones    5000
3        P004         Keyboard    3600
4        P005            Mouse    1800
5        P006           Tablet   22000
6        P007          Monitor   14500
7        P008          Printer   12000
8        P009       Smartwatch    9000
9        P010          Speaker    6400
10       P011           Camera   55000
11       P012       Power Bank    3000
12       P013           Router    2800
13       P014     External HDD   10400
14       P015        Pen Drive    1400
15       P016     Office Chair    8500
16       P017      Study Table   12500
17       P018  Air Conditioner   42000
18       P019     Refrigerator   38000
19       P020        Microwave   11000

In [81]:
# 64. Find the most popular product in each city

city_prod_qty = (final_df.groupby(["city", "product_name"])["quantity"].sum().reset_index())
idx_city = city_prod_qty.groupby("city")["quantity"].idxmax()
popular_city_prod = city_prod_qty.loc[idx_city]

In [82]:
# 65. Find total sales by state and category

state_cat_sales = (final_df.groupby(["state", "category"])["total_amount"].sum().reset_index())

In [83]:
# 66. Find total revenue generated by male customers

male_rev = final_df[final_df["gender"] == "Male"]["total_amount"].sum()

male_rev

np.int64(0)

In [84]:
# 67. Find total revenue generated by female customers

female_rev = final_df[final_df["gender"] == "Female"]["total_amount"].sum()

female_rev

np.int64(0)

In [85]:
# 68. Find the top 10 highest-value orders

top_10_orders = final_df.sort_values(by="total_amount", ascending=False).head(10)

top_10_orders.head()

,customer_id,customer_name,gender,city,state,signup_date,order_id,product_id,order_date,quantity,total_amount,payment_mode,order_status,product_name,category,brand,price,stock,rating
0,C001,Aarav Patel,M,Ahmedabad,Gujarat,2024-01-12,O001,P001,2025-01-05,1,65000,Credit Card,Delivered,Laptop,Electronics,HP,65000,15,4.5
18,C007,Rohan Desai,M,Vadodara,Gujarat,2024-03-19,O026,P001,2025-01-22,1,65000,Net Banking,Delivered,Laptop,Electronics,HP,65000,15,4.5
23,C010,Meera Kapoor,F,Chandigarh,Chandigarh,2024-02-26,O013,P011,2025-01-15,1,55000,Net Banking,Delivered,Camera,Electronics,Sony,55000,8,4.7
26,C012,Simran Kaur,F,Ludhiana,Punjab,2024-04-15,O016,P018,2025-01-17,1,42000,Credit Card,Pending,Air Conditioner,Home Appliances,LG,42000,7,4.6
29,C015,Aditya Rao,M,Hyderabad,Telangana,2024-03-12,O019,P019,2025-01-18,1,38000,Net Banking,Shipped,Refrigerator,Home Appliances,Samsung,38000,6,4.4

In [86]:
# 69. Find the city with the highest total sales

top_city = city_sales.loc[city_sales["total_amount"].idxmax()]

top_city

city            Ahmedabad
total_amount        90500
Name: 0, dtype: object

In [87]:
# 70. Find the brand generating the highest revenue

top_brand = brand_sales.loc[brand_sales["total_amount"].idxmax()]

top_brand

brand               HP
total_amount    136300
Name: 4, dtype: object

In [88]:
# 71. Find average spending per customer

avg_cust_spend = cust_spending["total_amount"].mean()

avg_cust_spend

np.float64(33420.0)

In [89]:
# 72. Find average spending per state

avg_state_spend = state_sales["total_amount"].mean()

avg_state_spend

np.float64(55700.0)

In [90]:
# 73. Find customers who purchased Electronics products

elec_customers = final_df[final_df["category"] == "Electronics"]["customer_name"].unique()

elec_customers

<StringArray>
[ 'Aarav Patel',  'Diya Sharma', 'Vivaan Mehta',   'Krish Shah',
  'Rohan Desai', 'Meera Kapoor']
Length: 6, dtype: str

In [91]:
# 74. Find customers who purchased products from multiple categories

cust_cat_counts = final_df.groupby("customer_name")["category"].nunique()
multi_cat_customers = cust_cat_counts[cust_cat_counts > 1].index.tolist()

cust_cat_counts
multi_cat_customers

['Aarav Patel',
 'Ananya Verma',
 'Diya Sharma',
 'Isha Joshi',
 'Kavya Nair',
 'Meera Kapoor',
 'Rohan Desai',
 'Vivaan Mehta']

In [92]:
# 75. Find the most ordered 

most_ordered_cat = final_df.groupby("category").size().idxmax()

most_ordered_cat

'Accessories'

In [93]:
# 76. Find revenue generated by each payment 

pay_mode_rev = final_df.groupby("payment_mode")["total_amount"].sum().reset_index()

pay_mode_rev

  payment_mode  total_amount
0         Cash         25800
1  Credit Card        158600
2   Debit Card         63000
3  Net Banking        180000
4          UPI         73900

In [94]:
# 77. Find the most preferred payment mode in each state

state_pay = final_df.groupby(["state", "payment_mode"]).size().reset_index(name="count")
idx_pay = state_pay.groupby("state")["count"].idxmax()
preferred_pay_state = state_pay.loc[idx_pay]

In [95]:
# 78. Find total quantity sold by category

cat_qty = final_df.groupby("category")["quantity"].sum().reset_index()

In [96]:
# 79. Find customers who placed only one order

single_order_cust = order_counts[order_counts["order_count"] == 1]["customer_name"].tolist()

In [97]:
# 80. Create a final report containing specified columns

final_report = final_df[["customer_name", "city", "product_name", "category", "quantity", "total_amount", "payment_mode", "order_status",]]

final_report

,customer_name,city,product_name,category,quantity,total_amount,payment_mode,order_status
0,Aarav Patel,Ahmedabad,Laptop,Electronics,1,65000,Credit Card,Delivered
1,Aarav Patel,Ahmedabad,Headphones,Accessories,2,5000,UPI,Delivered
2,Aarav Patel,Ahmedabad,Speaker,Accessories,1,3200,UPI,Shipped
3,Aarav Patel,Ahmedabad,Mouse,Accessories,4,3600,UPI,Delivered
4,Aarav Patel,Ahmedabad,External HDD,Storage,1,5200,Credit Card,Delivered
5,Diya Sharma,Mumbai,Smartphone,Electronics,1,28000,Debit Card,Cancelled
6,Diya Sharma,Mumbai,Monitor,Electronics,1,14500,Debit Card,Returned
7,Diya Sharma,Mumbai,Headphones,Accessories,1,2500,Cash,Delivered
8,Vivaan Mehta,Surat,Mouse,Accessories,3,2700,Cash,Delivered
9,Vivaan Mehta,Surat,Router,Networking,2,5600,UPI,Shipped
10,Vivaan Mehta,Surat,Smartphone,Electronics,1,28000,Credit Card,Delivered
11,Ananya Verma,Delhi,Keyboard,Accessories,2,3600,Credit Card,Delivered
12,Ananya Verma,Delhi,Smartwatch,Wearables,2,9000,UPI,Pending
13,Krish Shah,Rajkot,Tablet,Electronics,1,22000,Net Banking,Pending
14,Krish Shah,Rajkot,Printer,Electronics,1,12000,Debit Card,Delivered
15,Isha Joshi,Pune,Smartwatch,Wearables,2,9000,UPI,Delivered
16,Isha Joshi,Pune,Speaker,Accessories,3,9600,Credit Card,Returned
17,Rohan Desai,Vadodara,Power Bank,Accessories,3,4500,Cash,Delivered
18,Rohan Desai,Vadodara,Laptop,Electronics,1,65000,Net Banking,Delivered
19,Kavya Nair,Bengaluru,Pen Drive,Storage,5,3500,UPI,Delivered
20,Kavya Nair,Bengaluru,Keyboard,Accessories,2,3600,Cash,Delivered
21,Arjun Singh,Jaipur,External HDD,Storage,1,5200,Credit Card,Cancelled
22,Arjun Singh,Jaipur,Pen Drive,Storage,10,7000,UPI,Delivered
23,Meera Kapoor,Chandigarh,Camera,Electronics,1,55000,Net Banking,Delivered
24,Meera Kapoor,Chandigarh,Power Bank,Accessories,4,6000,UPI,Cancelled
25,Yash Trivedi,Ahmedabad,Office Chair,Furniture,1,8500,Debit Card,Delivered
26,Simran Kaur,Ludhiana,Air Conditioner,Home Appliances,1,42000,Credit Card,Pending
27,Dev Malhotra,Delhi,Study Table,Furniture,1,12500,Cash,Delivered
28,Riya Pandey,Patna,Microwave,Home Appliances,2,22000,UPI,Delivered
29,Aditya Rao,Hyderabad,Refrigerator,Home Appliances,1,38000,Net Banking,Shipped

#### 🟡 Join Type Practice Questions

In [98]:
import pandas as pd

In [99]:
pd.read_csv("../../dataset/products.csv").head()

  product_id product_name     category     brand  price  stock  rating
0       P001       Laptop  Electronics        HP  65000     15     4.5
1       P002   Smartphone  Electronics   Samsung  28000     30     4.3
2       P003   Headphones  Accessories      Boat   2500     50     4.1
3       P004     Keyboard  Accessories  Logitech   1800     40     4.4
4       P005        Mouse  Accessories        HP    900     60     4.0

In [100]:
pd.read_csv("../../dataset/orders.csv").head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped

In [101]:
pd.read_csv("../../dataset/orders2.csv").head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered
1,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending
2,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered
3,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered
4,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped

In [102]:
pd.read_csv("../../dataset/customers.csv").head()

  customer_id customer_name gender       city        state signup_date
0        C001   Aarav Patel      M  Ahmedabad      Gujarat  2024-01-12
1        C002   Diya Sharma      F     Mumbai  Maharashtra  2024-02-18
2        C003  Vivaan Mehta      M      Surat      Gujarat  2024-03-05
3        C004  Ananya Verma      F      Delhi        Delhi  2024-01-28
4        C005    Krish Shah      M     Rajkot      Gujarat  2024-04-10

In [103]:
pd.read_csv("../../dataset/payments.csv").head()

     name gender  amount month       city payment_method     category
0   Aarav      M  1200.0   Jan  Ahmedabad            UPI         Food
1  Vivaan      M  1500.0   Jan     Mumbai           Card     Shopping
2  Aditya      M     NaN   Jan      Delhi           Cash        Bills
3  Vihaan      M  1100.0   Jan       Pune            UPI    Transport
4   Arjun      M  2000.0   Jan  Bangalore           Card  Electronics

In [104]:
pd.read_csv("../../dataset/all_orders.csv").head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped

In [105]:
# 81. Perform an Inner Join between customers and orders

inner_join = pd.merge(customers, all_orders, on="customer_id", how="inner")

In [106]:
# 82. Count rows returned by the Inner Join

inner_rows = len(inner_join)

In [107]:
# 83. Perform a Left Join between customers and orders

left_join = pd.merge(customers, all_orders, on="customer_id", how="left")

In [108]:
# 84. Find customers who have no orders

cust_no_orders = left_join[left_join["order_id"].isna()]["customer_name"].unique()

In [109]:
# 85. Perform a Right Join between customers and orders

right_join = pd.merge(customers, all_orders, on="customer_id", how="right")

In [110]:
# 86. Find orders whose customer information is missing

orders_missing_cust = right_join[right_join["customer_name"].isna()]["order_id"].unique()

In [111]:
# 87. Perform an Outer Join between customers and orders

outer_join = pd.merge(customers, all_orders, on="customer_id", how="outer", indicator=True)

In [112]:
# 88. Identify rows that exist only in customers
only_customers = outer_join[outer_join["_merge"] == "left_only"]

In [113]:
# 89. Identify rows that exist only in orders

only_orders = outer_join[outer_join["_merge"] == "right_only"]

In [114]:
# 90. Use the _merge column to classify matched and unmatched records

outer_join["_merge"].value_counts()

_merge
both          30
left_only      5
right_only     0
Name: count, dtype: int64

#### 🟠 Advanced Concat Questions

In [115]:
import pandas as pd

In [116]:
pd.read_csv("../../dataset/products.csv").head()

  product_id product_name     category     brand  price  stock  rating
0       P001       Laptop  Electronics        HP  65000     15     4.5
1       P002   Smartphone  Electronics   Samsung  28000     30     4.3
2       P003   Headphones  Accessories      Boat   2500     50     4.1
3       P004     Keyboard  Accessories  Logitech   1800     40     4.4
4       P005        Mouse  Accessories        HP    900     60     4.0

In [117]:
pd.read_csv("../../dataset/orders.csv").head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped

In [118]:
pd.read_csv("../../dataset/orders2.csv").head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered
1,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending
2,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered
3,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered
4,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped

In [119]:
pd.read_csv("../../dataset/customers.csv").head()

  customer_id customer_name gender       city        state signup_date
0        C001   Aarav Patel      M  Ahmedabad      Gujarat  2024-01-12
1        C002   Diya Sharma      F     Mumbai  Maharashtra  2024-02-18
2        C003  Vivaan Mehta      M      Surat      Gujarat  2024-03-05
3        C004  Ananya Verma      F      Delhi        Delhi  2024-01-28
4        C005    Krish Shah      M     Rajkot      Gujarat  2024-04-10

In [120]:
pd.read_csv("../../dataset/payments.csv").head()

     name gender  amount month       city payment_method     category
0   Aarav      M  1200.0   Jan  Ahmedabad            UPI         Food
1  Vivaan      M  1500.0   Jan     Mumbai           Card     Shopping
2  Aditya      M     NaN   Jan      Delhi           Cash        Bills
3  Vihaan      M  1100.0   Jan       Pune            UPI    Transport
4   Arjun      M  2000.0   Jan  Bangalore           Card  Electronics

In [121]:
pd.read_csv("../../dataset/all_orders.csv").head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped

In [122]:
# 91. Add a column named source_file before concatenation

df1["source_file"] = "orders.csv"
df2["source_file"] = "orders2.csv"

In [123]:
# 92. Identify which file each order originated from

advanced_concat = pd.concat([df1, df2])

advanced_concat

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status,source_file
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered,orders.csv
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered,orders.csv
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled,orders.csv
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered,orders.csv
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped,orders.csv
5,O006,C004,P004,2025-01-11,2,3600,Credit Card,Delivered,orders.csv
6,O007,C005,P006,2025-01-11,1,22000,Net Banking,Pending,orders.csv
7,O008,C006,P009,2025-01-12,2,9000,UPI,Delivered,orders.csv
8,O009,C002,P007,2025-01-13,1,14500,Debit Card,Returned,orders.csv
9,O010,C007,P012,2025-01-13,3,4500,Cash,Delivered,orders.csv
10,O011,C008,P015,2025-01-14,5,3500,UPI,Delivered,orders.csv
11,O012,C009,P014,2025-01-15,1,5200,Credit Card,Cancelled,orders.csv
12,O013,C010,P011,2025-01-15,1,55000,Net Banking,Delivered,orders.csv
13,O014,C003,P013,2025-01-16,2,5600,UPI,Shipped,orders.csv
0,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered,orders2.csv
1,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending,orders2.csv
2,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered,orders2.csv
3,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered,orders2.csv
4,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped,orders2.csv
5,O020,C001,P005,2025-01-19,4,3600,UPI,Delivered,orders2.csv
6,O021,C002,P003,2025-01-19,1,2500,Cash,Delivered,orders2.csv
7,O022,C003,P002,2025-01-20,1,28000,Credit Card,Delivered,orders2.csv
8,O023,C004,P009,2025-01-20,2,9000,UPI,Pending,orders2.csv
9,O024,C005,P008,2025-01-21,1,12000,Debit Card,Delivered,orders2.csv
10,O025,C006,P010,2025-01-21,3,9600,Credit Card,Returned,orders2.csv
11,O026,C007,P001,2025-01-22,1,65000,Net Banking,Delivered,orders2.csv
12,O027,C008,P004,2025-01-22,2,3600,Cash,Delivered,orders2.csv
13,O028,C009,P015,2025-01-23,10,7000,UPI,Delivered,orders2.csv
14,O029,C010,P012,2025-01-23,4,6000,UPI,Cancelled,orders2.csv
15,O030,C001,P014,2025-01-24,1,5200,Credit Card,Delivered,orders2.csv

In [124]:
# 93. Compare total sales from orders.csv and orders2.csv

sales_comp = advanced_concat.groupby("source_file")["total_amount"].sum()

# sales_orders1 = df1["total_amount"].sum()
# sales_orders2 = df2["total_amount"].sum()

# sales_orders1, sales_orders2

# sales_orders2-sales_orders1

# df1

sales_comp

source_file
orders.csv     226800
orders2.csv    274500
Name: total_amount, dtype: int64

In [125]:
# 94. Compare total quantities sold from both files

qty_comp = advanced_concat.groupby("source_file")["quantity"].sum()

qty_comp

source_file
orders.csv     26
orders2.csv    36
Name: quantity, dtype: int64

In [126]:
# 95. Compare average order amount between both files

avg_comp = advanced_concat.groupby("source_file")["total_amount"].mean()

avg_comp

source_file
orders.csv     16200.00
orders2.csv    17156.25
Name: total_amount, dtype: float64

In [128]:
# 96. Find which file contains more orders

file_order_counts = advanced_concat["source_file"].value_counts()
more_orders_file = file_order_counts.idxmax()

file_order_counts, more_orders_file

(source_file
 orders2.csv    16
 orders.csv     14
 Name: count, dtype: int64,
 'orders2.csv')

In [129]:
# 97. Concatenate datasets while ignoring original indexes

concat_ignore_idx = pd.concat([df1, df2], ignore_index=True)

concat_ignore_idx

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status,source_file
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered,orders.csv
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered,orders.csv
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled,orders.csv
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered,orders.csv
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped,orders.csv
5,O006,C004,P004,2025-01-11,2,3600,Credit Card,Delivered,orders.csv
6,O007,C005,P006,2025-01-11,1,22000,Net Banking,Pending,orders.csv
7,O008,C006,P009,2025-01-12,2,9000,UPI,Delivered,orders.csv
8,O009,C002,P007,2025-01-13,1,14500,Debit Card,Returned,orders.csv
9,O010,C007,P012,2025-01-13,3,4500,Cash,Delivered,orders.csv
10,O011,C008,P015,2025-01-14,5,3500,UPI,Delivered,orders.csv
11,O012,C009,P014,2025-01-15,1,5200,Credit Card,Cancelled,orders.csv
12,O013,C010,P011,2025-01-15,1,55000,Net Banking,Delivered,orders.csv
13,O014,C003,P013,2025-01-16,2,5600,UPI,Shipped,orders.csv
14,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered,orders2.csv
15,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending,orders2.csv
16,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered,orders2.csv
17,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered,orders2.csv
18,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped,orders2.csv
19,O020,C001,P005,2025-01-19,4,3600,UPI,Delivered,orders2.csv
20,O021,C002,P003,2025-01-19,1,2500,Cash,Delivered,orders2.csv
21,O022,C003,P002,2025-01-20,1,28000,Credit Card,Delivered,orders2.csv
22,O023,C004,P009,2025-01-20,2,9000,UPI,Pending,orders2.csv
23,O024,C005,P008,2025-01-21,1,12000,Debit Card,Delivered,orders2.csv
24,O025,C006,P010,2025-01-21,3,9600,Credit Card,Returned,orders2.csv
25,O026,C007,P001,2025-01-22,1,65000,Net Banking,Delivered,orders2.csv
26,O027,C008,P004,2025-01-22,2,3600,Cash,Delivered,orders2.csv
27,O028,C009,P015,2025-01-23,10,7000,UPI,Delivered,orders2.csv
28,O029,C010,P012,2025-01-23,4,6000,UPI,Cancelled,orders2.csv
29,O030,C001,P014,2025-01-24,1,5200,Credit Card,Delivered,orders2.csv

In [130]:
# 98. Concatenate datasets while preserving original indexes

concat_preserve_idx = pd.concat([df1, df2], ignore_index=False)

concat_preserve_idx

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status,source_file
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered,orders.csv
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered,orders.csv
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled,orders.csv
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered,orders.csv
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped,orders.csv
5,O006,C004,P004,2025-01-11,2,3600,Credit Card,Delivered,orders.csv
6,O007,C005,P006,2025-01-11,1,22000,Net Banking,Pending,orders.csv
7,O008,C006,P009,2025-01-12,2,9000,UPI,Delivered,orders.csv
8,O009,C002,P007,2025-01-13,1,14500,Debit Card,Returned,orders.csv
9,O010,C007,P012,2025-01-13,3,4500,Cash,Delivered,orders.csv
10,O011,C008,P015,2025-01-14,5,3500,UPI,Delivered,orders.csv
11,O012,C009,P014,2025-01-15,1,5200,Credit Card,Cancelled,orders.csv
12,O013,C010,P011,2025-01-15,1,55000,Net Banking,Delivered,orders.csv
13,O014,C003,P013,2025-01-16,2,5600,UPI,Shipped,orders.csv
0,O015,C011,P016,2025-01-16,1,8500,Debit Card,Delivered,orders2.csv
1,O016,C012,P018,2025-01-17,1,42000,Credit Card,Pending,orders2.csv
2,O017,C013,P017,2025-01-17,1,12500,Cash,Delivered,orders2.csv
3,O018,C014,P020,2025-01-18,2,22000,UPI,Delivered,orders2.csv
4,O019,C015,P019,2025-01-18,1,38000,Net Banking,Shipped,orders2.csv
5,O020,C001,P005,2025-01-19,4,3600,UPI,Delivered,orders2.csv
6,O021,C002,P003,2025-01-19,1,2500,Cash,Delivered,orders2.csv
7,O022,C003,P002,2025-01-20,1,28000,Credit Card,Delivered,orders2.csv
8,O023,C004,P009,2025-01-20,2,9000,UPI,Pending,orders2.csv
9,O024,C005,P008,2025-01-21,1,12000,Debit Card,Delivered,orders2.csv
10,O025,C006,P010,2025-01-21,3,9600,Credit Card,Returned,orders2.csv
11,O026,C007,P001,2025-01-22,1,65000,Net Banking,Delivered,orders2.csv
12,O027,C008,P004,2025-01-22,2,3600,Cash,Delivered,orders2.csv
13,O028,C009,P015,2025-01-23,10,7000,UPI,Delivered,orders2.csv
14,O029,C010,P012,2025-01-23,4,6000,UPI,Cancelled,orders2.csv
15,O030,C001,P014,2025-01-24,1,5200,Credit Card,Delivered,orders2.csv

In [139]:
# 99. Find duplicate rows after concatenation

duplicate_rows = advanced_concat[advanced_concat.duplicated()]

duplicate_rows

display ("No Data Duplicated")

'No Data Duplicated'

In [140]:
# 100. Remove duplicate rows from the combined dataset

cleaned_concat = advanced_concat.drop_duplicates()

cleaned_concat.head()

,order_id,customer_id,product_id,order_date,quantity,total_amount,payment_mode,order_status,source_file
0,O001,C001,P001,2025-01-05,1,65000,Credit Card,Delivered,orders.csv
1,O002,C001,P003,2025-01-07,2,5000,UPI,Delivered,orders.csv
2,O003,C002,P002,2025-01-08,1,28000,Debit Card,Cancelled,orders.csv
3,O004,C003,P005,2025-01-08,3,2700,Cash,Delivered,orders.csv
4,O005,C001,P010,2025-01-10,1,3200,UPI,Shipped,orders.csv