#### 1. Total salary department-wise

In [ ]:
# 1. Find the total salary department-wise.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('department')['salary'].sum()

df

#### 2. Average salary department-wise

In [2]:
# 2. Find the average salary department-wise.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('department')['salary'].mean()

df

,user_id,age,gender,city,salary,experience_years,department,performance_score,joining_year
0,1,56.0,Female,Bangalore,NaN,3.0,IT,NaN,NaN
1,2,NaN,Male,Delhi,NaN,11.0,Finance,NaN,NaN
2,3,46.0,Male,NaN,55000.0,NaN,HR,5.0,2024.0
3,4,32.0,Male,Pune,NaN,1.0,Finance,NaN,2022.0
4,5,NaN,Male,Bangalore,115000.0,NaN,NaN,NaN,2024.0
...,...,...,...,...,...,...,...,...,...
995,996,NaN,Male,Pune,95000.0,NaN,Sales,NaN,2018.0
996,997,NaN,Female,Bangalore,NaN,7.0,Finance,NaN,2019.0
997,998,NaN,Female,Ahmedabad,65000.0,NaN,NaN,NaN,NaN
998,999,35.0,Other,Pune,140000.0,NaN,Finance,3.0,NaN
999,1000,55.0,Male,Pune,115000.0,14.0,NaN,2.0,NaN

#### 3. Remove rows where 'name' or 'gender' is missing

In [ ]:
# 3. Remove rows where 'name' or 'gender' is missing.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

# df.dropna(subset=['name', 'gender'], inplace=True)

df

#### 4. Create a pivot table showing total amount spent per month by gender.

In [ ]:
# 4. Create a pivot table showing total amount spent per month by gender.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

# df.pivot_table(values='amount', index='month', columns='gender', aggfunc='sum')

df

#### 5. Create a pivot table showing average spending per category in each city.

In [ ]:
# 5. Create a pivot table showing average spending per category in each city.

import pandas as pd

df = pd.read_csv("../../dataset/payments.csv")

df.pivot_table(values='amount', index='category', columns='city', aggfunc='mean')

df

#### 6. Create a pivot table to show count of transactions per payment method per month.

In [ ]:
# 6. Create a pivot table to show count of transactions per payment method per month.

import pandas as pd

df = pd.read_csv("../../dataset/payments.csv")

df.pivot_table(values='amount', index='payment_method', columns='month', aggfunc='count')

df

#### 7. Create a multi-level pivot table with index = (city, gender) and columns = month, showing total amount.

In [ ]:
# 7. Create a multi-level pivot table with index = (city, gender) and columns = month, showing total amount.

import pandas as pd

df = pd.read_csv("../../dataset/payments.csv")

df.pivot_table(values='amount', index=['city', 'gender'], columns='month', aggfunc='sum')

df

#### 8. Find the top 5 customers based on total spending.

In [ ]:
# 8. Find the top 5 customers based on total spending.

import pandas as pd

df = pd.read_csv("../../dataset/payments.csv")

df.groupby('name')['amount'].sum().nlargest(5)

df

#### 9. Create a pivot table showing total spending per category split by gender.

In [ ]:
# 9. Create a pivot table showing total spending per category split by gender.

import pandas as pd

df = pd.read_csv("../../dataset/payments.csv")

df.pivot_table(values='amount', index='category', columns='gender', aggfunc='sum')

df

#### 10. Create a pivot table (name vs month) with total amount and replace missing values with 0 using fill_value.

In [ ]:
# 10. Create a pivot table (name vs month) with total amount and replace missing values with 0 using fill_value.

import pandas as pd

df = pd.read_csv("../../dataset/payments.csv")

df.pivot_table(values='amount', index='name', columns='month', aggfunc='sum', fill_value=0)

df

#### 11. Find the minimum, maximum, and average salary department-wise.

In [17]:
# 11. Find the minimum, maximum, and average salary department-wise.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('department')['salary'].agg(['min', 'max', 'mean'])

df

,user_id,age,gender,city,salary,experience_years,department,performance_score,joining_year
0,1,56.0,Female,Bangalore,NaN,3.0,IT,NaN,NaN
1,2,NaN,Male,Delhi,NaN,11.0,Finance,NaN,NaN
2,3,46.0,Male,NaN,55000.0,NaN,HR,5.0,2024.0
3,4,32.0,Male,Pune,NaN,1.0,Finance,NaN,2022.0
4,5,NaN,Male,Bangalore,115000.0,NaN,NaN,NaN,2024.0
...,...,...,...,...,...,...,...,...,...
995,996,NaN,Male,Pune,95000.0,NaN,Sales,NaN,2018.0
996,997,NaN,Female,Bangalore,NaN,7.0,Finance,NaN,2019.0
997,998,NaN,Female,Ahmedabad,65000.0,NaN,NaN,NaN,NaN
998,999,35.0,Other,Pune,140000.0,NaN,Finance,3.0,NaN
999,1000,55.0,Male,Pune,115000.0,14.0,NaN,2.0,NaN

#### 12. Find total and average sales product-wise.

In [20]:
# 12. Find total and average sales product-wise.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('product')['sales'].agg(['sum', 'mean'])

df

KeyError: 'product'

#### 13. Find total quantity and total revenue category-wise.

In [22]:
# 13. Find total quantity and total revenue category-wise.

import pandas as pd

df = pd.read_csv("../../dataset/payments.csv")

df.groupby('category').agg({'quantity': 'sum', 'revenue': 'sum'})

df

KeyError: "Label(s) ['quantity', 'revenue'] do not exist"

#### 14. Find minimum and maximum marks subject-wise.

In [24]:
# 14. Find minimum and maximum marks subject-wise.

import pandas as pd

df = pd.read_csv("../../dataset/payments.csv")

df.groupby('subject')['marks'].agg(['min', 'max'])

df

KeyError: 'subject'

#### 15. Find count, mean, and sum of sales region-wise.

In [1]:
# 15. Find count, mean, and sum of sales region-wise.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('region')['sales'].agg(['count', 'mean', 'sum'])

df

KeyError: 'region'

#### 16. Total sales by Region and Product.

In [ ]:
# 16. Total sales by Region and Product.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby(['region', 'product'])['sales'].sum()

df

#### 17. Average salary by Department and Gender.

In [ ]:
# 17. Average salary by Department and Gender.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby(['department', 'gender'])['salary'].mean()

df

#### 18. Count employees by Department and Designation.

In [ ]:
# 18. Count employees by Department and Designation.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby(['department', 'designation'])['employee_id'].count()

df

#### 19. Total orders by Customer and Product.

In [ ]:
# 19. Total orders by Customer and Product.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby(['customer', 'product'])['order_id'].count()

df

#### 20. Average marks by Class and Subject.

In [ ]:
# 20. Average marks by Class and Subject.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby(['class', 'subject'])['marks'].mean()

df

#### 21. Total revenue by Category and City.

In [ ]:
# 21. Total revenue by Category and City.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby(['category', 'city'])['revenue'].sum()

df

#### 22. Maximum sales by Region and Salesperson.

In [ ]:
# 22. Maximum sales by Region and Salesperson.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby(['region', 'salesperson'])['sales'].max()

df

#### 23. Minimum salary by Department and Experience Level.

In [ ]:
# 23. Minimum salary by Department and Experience Level.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby(['department', 'experience_level'])['salary'].min()

df

#### 24. Count students by Class and Gender.

In [ ]:
# 24. Count students by Class and Gender.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby(['class', 'gender'])['student_id'].count()

df

#### 25. Average attendance by Class and Month.

In [ ]:
# 25. Average attendance by Class and Month.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby(['class', 'month'])['attendance'].mean()

df

#### 26. Find departments whose average salary is greater than 50,000.

In [ ]:
# 26. Find departments whose average salary is greater than 50,000.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

dept_avg = df.groupby('department')['salary'].mean()

dept_avg.loc[dept_avg > 50000]

df

#### 27. Products whose total sales exceed 1,00,000.

In [ ]:
# 27. Products whose total sales exceed 1,00,000.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

prod_sales = df.groupby('product')['sales'].sum()

prod_sales.loc[prod_sales > 100000]

df

#### 28. Department with the highest average salary.

In [ ]:
# 28. Department with the highest average salary.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('department')['salary'].mean().idxmax()

df

#### 29. City with the highest total sales.

In [ ]:
# 29. City with the highest total sales.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('city')['sales'].sum().idxmax()

df

#### 30. Top 3 departments based on total salary.

In [ ]:
# 30. Top 3 departments based on total salary.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('department')['salary'].sum().nlargest(3)

df

#### 31. Bottom 5 products based on sales.

In [ ]:
# 31. Bottom 5 products based on sales.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('product')['sales'].sum().nsmallest(5)

df

#### 32. Percentage contribution of each department to total salary.

In [ ]:
# 32. Percentage contribution of each department to total salary.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

(df.groupby('department')['salary'].sum() / df['salary'].sum()) * 100

df

#### 33. Percentage contribution of each region to total sales.

In [ ]:
# 33. Percentage contribution of each region to total sales.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

(df.groupby('region')['sales'].sum() / df['sales'].sum()) * 100

df

#### 34. Sort departments by average salary in descending order.

In [ ]:
# 34. Sort departments by average salary in descending order.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('department')['salary'].mean().sort_values(ascending=False)

df

#### 35. Departments having more than 20 employees.

In [ ]:
# 35. Departments having more than 20 employees.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

dept_count = df.groupby('department')['employee_id'].count()

dept_count.loc[dept_count > 20]

df

#### 36. Find salary range (max - min) department-wise.

In [ ]:
# 36. Find salary range (max - min) department-wise.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('department')['salary'].max() - df.groupby('department')['salary'].min()

#### 37. Find profit percentage category-wise.

In [26]:
# 37. Find profit percentage category-wise.

import pandas as pd

df = pd.read_csv("../../dataset/orders.csv")

df["Cost"] = df["Revenue"] / df["Quantity"] # new column

totals = df.groupby('Category')[['Revenue', 'Cost']].sum()
totals
(totals['Revenue'] / 100) * totals['Cost']

Category
Electronics    1.705600e+10
Furniture      1.176000e+09
dtype: float64

In [29]:
# 37. Find profit percentage category-wise.

import pandas as pd

df = pd.read_csv("../../dataset/orders.csv")

df["Cost"] = df["Revenue"] / df["Quantity"] # new column

# totals = df.groupby('Category')[['Revenue', 'Cost']].sum()
# totals
# (totals['Revenue'] / 100) * totals['Cost']

totals = df.groupby('Category')[['Revenue', 'Quantity']].sum()
totals

revenue_percentage = (totals / totals.sum()) * 100
revenue_percentage

               Revenue   Quantity
Category
Electronics  71.232877  36.180905
Furniture    28.767123  63.819095

In [30]:
import pandas as pd

df = pd.read_csv("../../dataset/orders.csv")

totals = df.groupby('Category')[['Revenue', 'Quantity']].sum()

totals['Revenue_Per_Unit'] = totals['Revenue'] / totals['Quantity']

print(totals[['Revenue_Per_Unit']])

             Revenue_Per_Unit
Category
Electronics      28888.888889
Furniture         6614.173228

In [31]:
totals = df.groupby('Category')['Revenue'].sum()

revenue_percentage = (totals / totals.sum()) * 100

print(revenue_percentage)

Category
Electronics    71.232877
Furniture      28.767123
Name: Revenue, dtype: float64

In [ ]:
# 38. Average order value customer-wise.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

df.groupby('customer_id')['order_value'].mean()

df

#### 39. Find the difference between highest and lowest sales region-wise.

In [7]:
# 39. Find the difference between highest and lowest sales region-wise.

import pandas as pd

df = pd.read_csv("../../dataset/orders.csv")

diff = df.groupby('Region')['Revenue'].max() - df.groupby('Region')['Revenue'].min()

diff

Region
East      90000
North    130000
South     95000
West     100000
Name: Revenue, dtype: int64

In [6]:
max = df.groupby('Region')['Revenue'].max()
min = df.groupby('Region')['Revenue'].min()

print(max)
print(min)

Region
East     120000
North    160000
South    120000
West     140000
Name: Revenue, dtype: int64
Region
East     30000
North    30000
South    25000
West     40000
Name: Revenue, dtype: int64

#### 40. Departments where the maximum salary is more than twice the minimum salary.

In [10]:
# 40. Departments where the maximum salary is more than twice the minimum salary.

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

salaries = df.groupby('department')['salary'].agg(['max', 'min'])

x = salaries.loc[salaries['max'] > (2 * salaries['min'])]
salaries

                 max      min
department
Finance     145000.0  20000.0
HR          145000.0  20000.0
IT          145000.0  20000.0
Sales       145000.0  20000.0

department
Finance    20000.0
HR         20000.0
IT         20000.0
Sales      20000.0
Name: salary, dtype: float64