#### 1. Display first 5 rows of dataset

In [5]:
# 1. Display first 5 rows of dataset

import pandas as pd

df = pd.read_csv("../../dataset/pandas_full_practice.csv")

print(df.head(5))

df.head(5)

   user_id   age  gender       city    salary  experience_years department  \
0        1  56.0  Female  Bangalore       NaN               3.0         IT
1        2   NaN    Male      Delhi       NaN              11.0    Finance
2        3  46.0    Male        NaN   55000.0               NaN         HR
3        4  32.0    Male       Pune       NaN               1.0    Finance
4        5   NaN    Male  Bangalore  115000.0               NaN        NaN

   performance_score  joining_year
0                NaN           NaN
1                NaN           NaN
2                5.0        2024.0
3                NaN        2022.0
4                NaN        2024.0

,user_id,age,gender,city,salary,experience_years,department,performance_score,joining_year
0,1,56.0,Female,Bangalore,NaN,3.0,IT,NaN,NaN
1,2,NaN,Male,Delhi,NaN,11.0,Finance,NaN,NaN
2,3,46.0,Male,NaN,55000.0,NaN,HR,5.0,2024.0
3,4,32.0,Male,Pune,NaN,1.0,Finance,NaN,2022.0
4,5,NaN,Male,Bangalore,115000.0,NaN,NaN,NaN,2024.0

#### 2. Display last 10 rows

In [20]:
# 2. Display last 10 rows

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

print(df.tail(10))

df.tail(10)

     user_id   age  gender       city    salary  experience_years department  \
990      991  24.0    Male       Pune       NaN              10.0         HR
991      992  20.0  Female  Ahmedabad   80000.0               NaN      Sales
992      993   NaN    Male      Delhi       NaN               NaN        NaN
993      994  40.0  Female        NaN  110000.0               NaN    Finance
994      995   NaN  Female      Delhi   75000.0               NaN    Finance
995      996   NaN    Male       Pune   95000.0               NaN      Sales
996      997   NaN  Female  Bangalore       NaN               7.0    Finance
997      998   NaN  Female  Ahmedabad   65000.0               NaN        NaN
998      999  35.0   Other       Pune  140000.0               NaN    Finance
999     1000  55.0    Male       Pune  115000.0              14.0        NaN

     performance_score  joining_year
990                NaN        2024.0
991                NaN        2013.0
992                2.0           NaN
993                1.0        2014.0
994                NaN           NaN
995                NaN        2018.0
996                NaN        2019.0
997                NaN           NaN
998                3.0           NaN
999                2.0           NaN

,user_id,age,gender,city,salary,experience_years,department,performance_score,joining_year
990,991,24.0,Male,Pune,NaN,10.0,HR,NaN,2024.0
991,992,20.0,Female,Ahmedabad,80000.0,NaN,Sales,NaN,2013.0
992,993,NaN,Male,Delhi,NaN,NaN,NaN,2.0,NaN
993,994,40.0,Female,NaN,110000.0,NaN,Finance,1.0,2014.0
994,995,NaN,Female,Delhi,75000.0,NaN,Finance,NaN,NaN
995,996,NaN,Male,Pune,95000.0,NaN,Sales,NaN,2018.0
996,997,NaN,Female,Bangalore,NaN,7.0,Finance,NaN,2019.0
997,998,NaN,Female,Ahmedabad,65000.0,NaN,NaN,NaN,NaN
998,999,35.0,Other,Pune,140000.0,NaN,Finance,3.0,NaN
999,1000,55.0,Male,Pune,115000.0,14.0,NaN,2.0,NaN

#### 3. Find shape of dataset (rows, columns)

In [21]:
# 3. Find shape of dataset (rows, columns)

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df.shape

(1000, 9)

#### 4. Print all column names

In [22]:
# 4. Print all column names

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df.columns

Index(['user_id', 'age', 'gender', 'city', 'salary', 'experience_years',
       'department', 'performance_score', 'joining_year'],
      dtype='str')

#### 5. Check data types of each column

In [23]:
# 5. Check data types of each column

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df.dtypes

user_id                int64
age                  float64
gender                   str
city                     str
salary               float64
experience_years     float64
department               str
performance_score    float64
joining_year         float64
dtype: object

#### 6. Use info() and observe non-null counts

In [24]:
# 6. Use info() and observe non-null counts

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            1000 non-null   int64
 1   age                806 non-null    float64
 2   gender             952 non-null    str
 3   city               824 non-null    str
 4   salary             549 non-null    float64
 5   experience_years   572 non-null    float64
 6   department         806 non-null    str
 7   performance_score  482 non-null    float64
 8   joining_year       741 non-null    float64
dtypes: float64(5), int64(1), str(3)
memory usage: 70.4 KB

#### 7. Use describe() for numeric columns

In [25]:
# 7. Use describe() for numeric columns

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df.describe()

,user_id,age,salary,experience_years,performance_score,joining_year
count,1000.000000,806.000000,549.000000,572.000000,482.000000,741.000000
mean,500.500000,38.767990,83306.010929,7.255245,2.931535,2016.766532
std,288.819436,12.057915,37424.488210,4.318480,1.416227,4.275418
min,1.000000,18.000000,20000.000000,0.000000,1.000000,2010.000000
25%,250.750000,29.000000,50000.000000,4.000000,2.000000,2013.000000
50%,500.500000,40.000000,80000.000000,7.000000,3.000000,2016.000000
75%,750.250000,49.000000,115000.000000,11.000000,4.000000,2021.000000
max,1000.000000,59.000000,145000.000000,14.000000,5.000000,2024.000000

#### 8. Use describe(include='object') for categorical

In [26]:
# 8. Use describe(include='object') for categorical

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df.describe(include="object")

C:\Users\tapan\AppData\Local\Temp\ipykernel_21404\3909367587.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

        gender       city department
count      952        824        806
unique       3          5          4
top     Female  Bangalore    Finance
freq       457        190        221

#### 9. Count unique values in each column

In [27]:
# 9. Count unique values in each column

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df.nunique()

user_id              1000
age                    42
gender                  3
city                    5
salary                 26
experience_years       15
department              4
performance_score       5
joining_year           15
dtype: int64

#### 10.

In [28]:
# 10.

#### 11. Find mean salary

In [29]:
# 11. Find mean salary

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

mean_salary = df["salary"].mean()

print(mean_salary)

mean_salary

83306.01092896175

np.float64(83306.01092896175)

#### 12. Find maximum and minimum age

In [30]:
# 12. Find maximum and minimum age

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

max_age = df["age"].max()
min_age = df["age"].min()

print(f"Maximum age: {max_age}")
print(f"Minimum age: {min_age}")

Maximum age: 59.0
Minimum age: 18.0

#### 13. Count total users in each department

In [31]:
# 13. Count total users in each department

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

department_counts = df["department"].value_counts()

print(department_counts)

department_counts

department
Finance    221
Sales      208
HR         196
IT         181
Name: count, dtype: int64

department
Finance    221
Sales      208
HR         196
IT         181
Name: count, dtype: int64

#### 14. Find most frequent city

In [32]:
# 14. Find most frequent city

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

most_frequent_city = df["city"].mode()[0]  # AI

print(f"Most frequent city: {most_frequent_city}")

most_frequent_city

Most frequent city: Bangalore

'Bangalore'

#### 15. Count gender distribution

In [33]:
# 15. Count gender distribution

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

gender_distribution = df["gender"].value_counts()

print(gender_distribution)

gender_distribution

gender
Female    457
Male      448
Other      47
Name: count, dtype: int64

gender
Female    457
Male      448
Other      47
Name: count, dtype: int64

#### 16. Filter users with salary > 100000

In [34]:
# 16. Filter users with salary > 100000

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

high_salary_users = df[df["salary"] > 100000]

print(high_salary_users)

high_salary_users

     user_id   age  gender       city    salary  experience_years department  \
4          5   NaN    Male  Bangalore  115000.0               NaN        NaN
6          7  38.0    Male  Ahmedabad  145000.0               NaN         IT
8          9  36.0    Male        NaN  120000.0               4.0    Finance
13        14  53.0  Female     Mumbai  135000.0               NaN      Sales
17        18  39.0  Female        NaN  135000.0               NaN         IT
..       ...   ...     ...        ...       ...               ...        ...
980      981  43.0     NaN  Bangalore  110000.0               1.0         IT
984      985  41.0  Female      Delhi  110000.0               6.0    Finance
993      994  40.0  Female        NaN  110000.0               NaN    Finance
998      999  35.0   Other       Pune  140000.0               NaN    Finance
999     1000  55.0    Male       Pune  115000.0              14.0        NaN

     performance_score  joining_year
4                  NaN        2024.0
6                  NaN           NaN
8                  3.0        2013.0
13                 1.0           NaN
17                 NaN           NaN
..                 ...           ...
980                NaN        2023.0
984                NaN        2018.0
993                1.0        2014.0
998                3.0           NaN
999                2.0           NaN

[195 rows x 9 columns]

,user_id,age,gender,city,salary,experience_years,department,performance_score,joining_year
4,5,NaN,Male,Bangalore,115000.0,NaN,NaN,NaN,2024.0
6,7,38.0,Male,Ahmedabad,145000.0,NaN,IT,NaN,NaN
8,9,36.0,Male,NaN,120000.0,4.0,Finance,3.0,2013.0
13,14,53.0,Female,Mumbai,135000.0,NaN,Sales,1.0,NaN
17,18,39.0,Female,NaN,135000.0,NaN,IT,NaN,NaN
...,...,...,...,...,...,...,...,...,...
980,981,43.0,NaN,Bangalore,110000.0,1.0,IT,NaN,2023.0
984,985,41.0,Female,Delhi,110000.0,6.0,Finance,NaN,2018.0
993,994,40.0,Female,NaN,110000.0,NaN,Finance,1.0,2014.0
998,999,35.0,Other,Pune,140000.0,NaN,Finance,3.0,NaN
999,1000,55.0,Male,Pune,115000.0,14.0,NaN,2.0,NaN

#### 17. Filter users from Ahmedabad

In [35]:
# 17. Filter users from Ahmedabad

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

ahmedabad_users = df[df["city"] == "Ahmedabad"]

print(ahmedabad_users)

ahmedabad_users

     user_id   age  gender       city    salary  experience_years department  \
6          7  38.0    Male  Ahmedabad  145000.0               NaN         IT
7          8  56.0    Male  Ahmedabad       NaN               NaN         IT
14        15  57.0    Male  Ahmedabad       NaN               2.0         HR
23        24  19.0  Female  Ahmedabad   70000.0               7.0         IT
27        28  39.0    Male  Ahmedabad   80000.0               NaN      Sales
..       ...   ...     ...        ...       ...               ...        ...
978      979  39.0    Male  Ahmedabad  135000.0               NaN    Finance
987      988  43.0     NaN  Ahmedabad       NaN              13.0        NaN
988      989  31.0    Male  Ahmedabad   95000.0               NaN         HR
991      992  20.0  Female  Ahmedabad   80000.0               NaN      Sales
997      998   NaN  Female  Ahmedabad   65000.0               NaN        NaN

     performance_score  joining_year
6                  NaN           NaN
7                  NaN        2021.0
14                 5.0        2021.0
23                 NaN           NaN
27                 NaN        2022.0
..                 ...           ...
978                NaN        2019.0
987                1.0           NaN
988                NaN        2022.0
991                NaN        2013.0
997                NaN           NaN

[162 rows x 9 columns]

,user_id,age,gender,city,salary,experience_years,department,performance_score,joining_year
6,7,38.0,Male,Ahmedabad,145000.0,NaN,IT,NaN,NaN
7,8,56.0,Male,Ahmedabad,NaN,NaN,IT,NaN,2021.0
14,15,57.0,Male,Ahmedabad,NaN,2.0,HR,5.0,2021.0
23,24,19.0,Female,Ahmedabad,70000.0,7.0,IT,NaN,NaN
27,28,39.0,Male,Ahmedabad,80000.0,NaN,Sales,NaN,2022.0
...,...,...,...,...,...,...,...,...,...
978,979,39.0,Male,Ahmedabad,135000.0,NaN,Finance,NaN,2019.0
987,988,43.0,NaN,Ahmedabad,NaN,13.0,NaN,1.0,NaN
988,989,31.0,Male,Ahmedabad,95000.0,NaN,HR,NaN,2022.0
991,992,20.0,Female,Ahmedabad,80000.0,NaN,Sales,NaN,2013.0
997,998,NaN,Female,Ahmedabad,65000.0,NaN,NaN,NaN,NaN

#### 18. Filter users with experience > 5 years

In [36]:
# 18. Filter users with experience > 5 years

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

experienced_users = df[df["experience"] > 5]

print(experienced_users)

experienced_users

KeyError: 'experience'

#### 19. Filter IT department with salary > 80000

In [ ]:
# 19. Filter IT department with salary > 80000

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

it_high_salary_users = df[(df["department"] == "IT") & (df["salary"] > 80000)]

print(it_high_salary_users)

it_high_salary_users

#### 20. Select only numeric columns

In [ ]:
# 20. Select only numeric columns

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

numeric_columns = df.select_dtypes(include="number")

print(numeric_columns)

numeric_columns

#### 21. Sort dataset by salary (descending)

In [ ]:
# 21. Sort dataset by salary (descending)

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

sorted_by_salary = df.sort_values(by="salary", ascending=False)

print(sorted_by_salary)

sorted_by_salary

#### 22. Get top 10 highest salary users

In [ ]:
# 22. Get top 10 highest salary users

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

top_10_highest_salary_users = df.sort_values(by="salary", ascending=False).head(10)

print(top_10_highest_salary_users)

top_10_highest_salary_users

#### 23. Sort by age and experience_years

In [ ]:
# 23. Sort by age and experience_years

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

sorted_by_age_experience = df.sort_values(
    by=["age", "experience"], ascending=[True, True]
)  # AI

print(sorted_by_age_experience)

sorted_by_age_experience

#### 24. Rank users based on salary

In [ ]:
# 24. Rank users based on salary

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df["salary_rank"] = df["salary"].rank(ascending=False)

print(df[["name", "salary", "salary_rank"]])  # name is not in dataset

df[["name", "salary", "salary_rank"]]

In [ ]:
import pandas as pd

df = pd.read_csv("../pandas_practice/dataset/pandas_full_practice.csv")

salary_sort = df.sort_values(by="salary").reset_index(drop=True)
salary_sort

#### 25. Find youngest user

In [ ]:
# 25. Find youngest user

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

youngest_user = df[df["age"] == df["age"].min()]

print(youngest_user)

youngest_user

#### 26. Find average salary per department

In [ ]:
# 26. Find average salary per department

import pandas as pd

df = pd.read_csv("..\dataset\pandas_full_practice.csv")

average_salary_per_department = df.groupby("department")["salary"].mean()

print(average_salary_per_department)

average_salary_per_department

#### 27. Count users per city

In [ ]:
# 27. Count users per city

import pandas as pd

df = pd.read_csv("..\dataset\pandas_full_practice.csv")

users_per_city = df["city"].value_counts()

print(users_per_city)

users_per_city

#### 27. Count users per city

In [ ]:
# 27. Count users per city

import pandas as pd

df = pd.read_csv("..\dataset\pandas_full_practice.csv")

users_per_city = df["city"].value_counts()

print(users_per_city)

users_per_city

#### 28. Find max salary per gender

In [ ]:
# 28. Find max salary per gender

import pandas as pd

df = pd.read_csv("..\dataset\pandas_full_practice.csv")

max_salary_per_gender = df.groupby("gender")["salary"].max()

print(max_salary_per_gender)

max_salary_per_gender

#### 29. Find average experience per department

In [ ]:
# 29. Find average experience per department

import pandas as pd

df = pd.read_csv("..\dataset\pandas_full_practice.csv")

average_experience_per_department = df.groupby("department")["experience"].mean()

print(average_experience_per_department)

average_experience_per_department

#### 30. Group by city and department

In [ ]:
# 30. Group by city and department

import pandas as pd

df = pd.read_csv("..\dataset\pandas_full_practice.csv")

grouped_city_department = df.groupby(["city", "department"]).size()

print(grouped_city_department)

grouped_city_department

#### 31. Create new column salary_category (Low/Medium/High)

In [ ]:
# 31. Create new column salary_category (Low/Medium/High)

import pandas as pd

df = pd.read_csv("..\dataset\pandas_full_practice.csv")


def categorize_salary(salary):

    if salary < 50000:
        return "Low"
    elif salary < 100000:
        return "Medium"
    else:
        return "High"


df["salary_category"] = df["salary"].apply(categorize_salary)

print(df[["salary", "salary_category"]])

df[["salary", "salary_category"]]

#### 32. Create experience_level column

In [ ]:
# 32. Create experience_level column

import pandas as pd

df = pd.read_csv("..\dataset\pandas_full_practice.csv")


def categorize_experience(experience):

    if experience < 2:
        return "Junior"
    elif experience < 5:
        return "Mid"
    else:
        return "Senior"


df["experience_level"] = df["experience"].apply(categorize_experience)

print(df[["experience", "experience_level"]])

df[["experience", "experience_level"]]

#### 33. Create age_group column

In [ ]:
# 33. Create age_group column

import pandas as pd

df = pd.read_csv("..\dataset\pandas_full_practice.csv")

df.dropna(subset=["age"], inplace=True)


def categorize_age(age):

    if age < 30:
        return "Young"
    elif age < 50:
        return "Middle-aged"
    else:
        return "Senior"


df["age_group"] = df["age"].apply(categorize_age)

# print(df[['age', 'age_group']])

df[["age", "age_group"]]

#### 34. Create salary_per_experience column

In [ ]:
# 34. Create salary_per_experience column

import pandas as pd

df = pd.read_csv("..\\dataset\\pandas_full_practice.csv")


def salary_per_experience(x):

    # if pd.isna(experience_years):
    #     return None

    if x["experience_years"] < 15:
        return x["salary"] + 120000
    elif x["experience_years"] < 10:
        return x["experience_years"] + 100000
    else:
        return 80000


# df["experience_years"].min(), df["experience_years"].max()


df["new_salary"] = df.apply(salary_per_experience, axis=1)
df

In [ ]:
# 34. Create salary_per_experience column

import pandas as pd

df = pd.read_csv("..\\dataset\\pandas_full_practice.csv")


def salary_per_experience(x):

    # if pd.isna(experience_years):
    #     return None
    # if x["experience_years"] < 15:
    #     return x["salary"] + 120000
    # elif x["experience_years"] < 10:
    #     return x["experience_years"] + 100000
    # else:
    #     return 80000

    print(x)


# df["experience_years"].min(), df["experience_years"].max()


df["new_salary"] = df.apply(salary_per_experience, axis=1)
df

#### 35. Create high_performer column (score >= 4)

In [ ]:
# 35. Create high_performer column (score >= 4)

import pandas as pd

df = pd.read_csv("..\\dataset\\pandas_full_practice.csv")


def high_performer(x):
    if x["performance_score"] >= 4:
        return "yes"
    else:
        return "no"


df["high_performer"] = df.apply(high_performer, axis=1)
df

#### 36. Count missing values per column

In [ ]:
# 36. Count missing values per column

import pandas as pd

df = pd.read_csv("..\\dataset\\pandas_full_practice.csv")

df
missing_values = df.isna().sum()

# df["user_id"].isna().sum(axis=0)
# df["age"].isna().sum(axis=0)
# df["gender"].isna().sum(axis=0)
# df["city"].isna().sum(axis=0)
# df["salary"].isna().sum(axis=0)
# df["experience_years"].isna().sum(axis=0)
# df["department"].isna().sum(axis=0)
# df["performance_score"].isna().sum(axis=0)
# df["joining_year"].isna().sum(axis=0)

missing_values

#### 37. Calculate percentage of missing values

In [ ]:
# 37. Calculate percentage of missing values

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

missing_percentage = (df.isna().sum() / len(df)) * 100  # len?

missing_percentage

#### 38. Find column with highest missing values

In [ ]:
import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

missing_counts = df.isna().sum()

column_with_max_missing = missing_counts.idxmax()
max_missing_count = missing_counts.max()

print(f"Column: {column_with_max_missing}")
print(f"Missing Values: {max_missing_count}")

#### 39. Count rows with any missing values

In [ ]:
# 39. Count rows with any missing values

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

rows_with_missing_values = df.isna().any(axis=1).sum()

print(f"Number of rows with any missing values: {rows_with_missing_values}")

#### 40. Count rows where all values are missing

In [ ]:
# 40. Count rows where all values are missing

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

rows_with_all_missing_values = df.isna().all(axis=1).sum()

print(f"Number of rows where all values are missing: {rows_with_all_missing_values}")

#### 41. Drop rows where age is missing

In [ ]:
# 41. Drop rows where age is missing

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df_dropped_age_missing = df.dropna(subset=["age"])

print(df_dropped_age_missing)

#### 42. Drop columns with more than 25% missing values

In [ ]:
# 42. Drop columns with more than 25% missing values

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

missing_percentage = (df.isna().sum() / len(df)) * 100

columns_to_drop = missing_percentage[missing_percentage > 25].index

df_dropped_columns = df.drop(columns=columns_to_drop)

print(df_dropped_columns)

#### 43. Fill missing age with mean

In [ ]:
# 43. Fill missing age with mean

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

mean_age = df["age"].mean()

df["age_filled"] = df["age"].fillna(mean_age)

print(df[["age", "age_filled"]])

df[["age", "age_filled"]]

#### 44. Fill missing salary with median

In [ ]:
# 44. Fill missing salary with median

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

median_salary = df["salary"].median()

df["salary_filled"] = df["salary"].fillna(median_salary)

print(df[["salary", "salary_filled"]])

df[["salary", "salary_filled"]]

#### 45. Fill missing gender with mode

In [ ]:
# 45. Fill missing gender with mode

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

mode_gender = df["gender"].mode()[0]

df["gender_filled"] = df["gender"].fillna(mode_gender)

print(df[["gender", "gender_filled"]])

df[["gender", "gender_filled"]]

#### 46. Fill salary using department-wise median

In [ ]:
# 46. Fill salary using department-wise median

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

dept_median = df.groupby("department")["salary"].transform("median")

df["salary_filled_department_median"] = df["salary"].fillna(dept_median)

print(df[["department", "salary", "salary_filled_department_median"]])

df[["department", "salary", "salary_filled_department_median"]]

#### 47. Fill age using city-wise mean

In [ ]:
# 47. Fill age using city-wise mean

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

city_mean = df.groupby("city")["age"].transform("mean")

df["age_filled_city_mean"] = df["age"].fillna(city_mean)

print(df[["city", "age", "age_filled_city_mean"]])

df[["city", "age", "age_filled_city_mean"]]

#### 48. Forward fill performance_score

In [ ]:
# 48. Forward fill performance_score

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df["performance_score_filled"] = df["performance_score"].fillna(method="ffill")

print(df[["performance_score", "performance_score_filled"]])

df[["performance_score", "performance_score_filled"]]

#### 49. Backward fill joining_year

In [ ]:
# 49. Backward fill joining_year

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df["joining_year_filled"] = df["joining_year"].fillna(method="bfill")

print(df[["joining_year", "joining_year_filled"]])

df[["joining_year", "joining_year_filled"]]

#### 50. Fill missing department with "Unknown"

In [ ]:
# 50. Fill missing department with "Unknown"

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df["department_filled"] = df["department"].fillna("Unknown")

print(df[["department", "department_filled"]])

df[["department", "department_filled"]]

#### 51. If experience_years is 0, fill salary with minimum salary

In [ ]:
# 51. If experience_years is 0, fill salary with minimum salary

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

min_salary = df["salary"].min()

df.loc[df["experience_years"] == 0, "salary"] = df.loc[
    df["experience_years"] == 0, "salary"
].fillna(min_salary)

print(df[["experience_years", "salary"]])

df[["experience_years", "salary"]]

#### 52. Fill missing age using average age of same experience_years

In [ ]:
# 52. Fill missing age using average age of same experience_years

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

experience_years_mean_age = df.groupby("experience_years")["age"].transform("mean")

df["age_filled_experience_mean"] = df["age"].fillna(experience_years_mean_age)

print(df[["experience_years", "age", "age_filled_experience_mean"]])

df[["experience_years", "age", "age_filled_experience_mean"]]

#### 53. Fill categorical missing values using group mode

In [ ]:
# 53. Fill categorical missing values using group mode

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

group_mode = df.groupby("department")["city"].agg(pd.Series.mode).str[0]
df["filled_group_mode"] = df["city"].fillna(df["department"].map(group_mode))

print(df[["department", "city", "filled_group_mode"]])
df[["department", "city", "filled_group_mode"]]

#### 54. Drop rows where both age and salary are missing

In [ ]:
# 54. Drop rows where both age and salary are missing

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df_dropped_age_missing = df.dropna(subset=["age"])
df_dropped_salary_missing = df.dropna(subset=["salary"])

print(df_dropped_age_missing)
print(df_dropped_salary_missing)

#### 55. Create column is_salary_missing (1 if missing else 0)

In [ ]:
# 55. Create column is_salary_missing (1 if missing else 0)

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")


def salary_category(x):
    if pd.isna(x):
        return 1
    else:
        return 0


df["salary_missing"] = df["salary"].apply(salary_category)

abc = (df.groupby("salary_missing")["user_id"].count().reset_index(name="user_count", drop=False))

abc

#### 56. Compare mean salary before and after filling missing values

In [37]:
# 56. Compare mean salary before and after filling missing values

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

dept_median = df.groupby("department")["salary"].transform("median")
df["salary_filled"] = df["salary"].fillna(dept_median)

mean_before = df["salary"].mean()
mean_after = df["salary_filled"].mean()

print(f"Mean salary before filling: {mean_before}")
print(f"Mean salary after filling: {mean_after}")

Mean salary before filling: 83306.01092896175
Mean salary after filling: 84300.7769145394

#### 57. Check if any missing values remain

In [38]:
# 57. Check if any missing values remain

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df.isna().sum()

user_id                0
age                  194
gender                48
city                 176
salary               451
experience_years     428
department           194
performance_score    518
joining_year         259
dtype: int64

#### 58. Recalculate summary statistics after cleaning

In [ ]:
# 58. Recalculate summary statistics after cleaning

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df.describe()

#### 59. Validate no invalid values (negative salary, etc.)

In [ ]:
# 59. Validate no invalid values (negative salary, etc.)

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df_dropped_salary_missing = df.dropna(subset=["salary"])

print(df_dropped_salary_missing)

In [ ]:
a = df[df["salary"] < 0]
a

#### 60. Save cleaned dataset to new CSV file

In [ ]:
# 60. Save cleaned dataset to new CSV file

import pandas as pd

df = pd.read_csv("../dataset/pandas_full_practice.csv")

df.to_csv("../dataset/new_pandas_full_practice.csv")